// Inventory is broader than the implemented registry. A family is never marked
// complete merely because it has a constructor or an old-page link.
export const families = [
  { id: 'context', sources: ['matrix_calculator.html', 'js/matrix_calculator.js'], assets: ['coefficientRing', 'field', 'basis', 'parameters'], fields: ['domain', 'characteristic', 'generators', 'relations', 'basis'], dependencies: [], views: ['data'], formats: ['project-json'], limitations: ['General algebraic contexts are not yet independently constructible.'] },
  { id: 'young', sources: ['young_diagrams.html', 'js/young_diagrams.js'], assets: ['partition', 'skew', 'tableaux', 'hookTable'], fields: ['rows', 'outer', 'inner', 'entries', 'content'], dependencies: ['partition'], views: ['partition', 'tableaux', 'data'], formats: ['project-json', 'recipe', 'partition-text', 'legacy-young-json'], limitations: ['Generalised signed rows, all tableau visualisations, legacy LaTeX and SVG interchange remain to migrate.'] },
  { id: 'representation', sources: ['double_young_diagram.html', 'double_young_diagram_production_process.html', 'js/double_young_diagram.js'], assets: ['representation', 'decomposition', 'symmetricFunction', 'symmetricPolynomial', 'classExpression'], fields: ['rows', 'labels', 'type', 'rank', 'terms', 'basis', 'variables', 'coefficients'], dependencies: ['partition', 'rootSystem'], views: ['decomposition', 'data'], formats: ['project-json', 'recipe', 'legacy-double-young-json'], limitations: ['Extracted functions retain legacy floating-point algorithms and caps; general symmetric-function controls, branching and production-process views remain to migrate.'] },
  { id: 'dynkin', sources: ['dynkin_diagram_calculator.html', 'js/dynkin_diagram_calculator.js'], assets: ['rootSystem', 'root', 'weight', 'rootSubsystem', 'quiver'], fields: ['type', 'rank', 'coordinates', 'basis', 'selectedVertices', 'orientations'], dependencies: ['rootSystem'], views: ['dynkin', 'points', 'data'], formats: ['project-json', 'recipe'], limitations: ['Parabolic, quiver, starting-function and Auslander–Reiten workflows remain to migrate.'] },
  { id: 'matrix', sources: ['matrix_calculator.html', 'js/matrix_calculator.js'], assets: ['matrix', 'vector', 'linearMap', 'polynomial'], fields: ['rows', 'ring', 'source', 'target', 'basis', 'terms'], dependencies: ['coefficientRing', 'basis'], views: ['matrix', 'data'], formats: ['project-json', 'recipe', 'matrix-rows', 'sage-matrix', 'macaulay2-matrix'], limitations: ['Workspace matrix arithmetic currently supports QQ and ZZ. Numerical, finite-field, function-field, number-field, canonical-form and polynomial-action features remain to migrate.', 'Generated CAS snippets are not execution-verified on this machine.'] },
  { id: 'geometry', sources: ['higher_dimensional_slice_calculator.html', 'js/higher_dimensional_slice_explorer.js', 'js/toric_cone_math.js'], assets: ['points', 'polytope', 'sphere', 'frame', 'cone', 'fan'], fields: ['points', 'edges', 'dimension', 'origin', 'basis', 'generators', 'cones'], dependencies: ['matrix', 'rootSystem'], views: ['points', 'data'], formats: ['project-json', 'recipe'], limitations: ['Interactive affine slicing, camera controls, regular-polytope builders and complete toric view interactions remain to migrate.'] },
  { id: 'sheaf', sources: ['sheaf_calculator.html', 'js/sheaf_calculator.js'], assets: ['variety', 'sheaf', 'varietyMap', 'sheafMap', 'divisor', 'classExpression', 'invariantTable'], fields: ['kind', 'type', 'dimension', 'base', 'rank', 'factors', 'source', 'target', 'traits', 'assumptions'], dependencies: ['variety', 'sheaf', 'varietyMap'], views: ['data'], formats: ['project-json', 'recipe'], limitations: ['Only explicitly registered formulas are available. Full characteristic-class, homology-rule, map and cohomology coverage remains to migrate.'], proposedSources: ['sheaf_calculator_next/analysis/type_hierarchy.md'], proposedOnly: ['A type listed in the rebuild draft is not evidence of a working constructor.'] },
  { id: 'complex', sources: ['sheaf_complex_calculator.html', 'js/sheaf_complex_calculator.js'], assets: ['sheafComplex', 'complexChart'], fields: ['terms', 'degrees', 'differentials', 'base'], dependencies: ['sheaf', 'sheafMap'], views: ['data'], formats: ['project-json'], limitations: ['Legacy complex-chart interactions and computations remain to migrate.'] },
  { id: 'mosaic', sources: ['mosaic_calculator.html', 'js/mosaic_calculator.js', 'js/background_homology.js'], assets: ['surface', 'cellComplex', 'path', 'knotDiagram', 'linkDiagram', 'dualGraph', 'metric'], fields: ['lattice', 'rows', 'cols', 'activeTiles', 'gluedEdges', 'vertices', 'edges', 'faces', 'chains', 'metric'], dependencies: ['surface'], views: ['surface', 'data'], formats: ['project-json', 'recipe'], limitations: ['Uses the existing BackgroundHomology engine snapshot format. Full mosaic presets, polygon gluing editor, knot/link, metric, uniformisation and degeneration tools remain to migrate.', 'Games remain in their separate application.'] },
  { id: 'category', sources: ['category_calculator.html', 'js/category_calculator.js'], assets: ['category', 'functor'], fields: ['objects', 'morphisms', 'conditions', 'source', 'target', 'objectMap', 'morphismMap'], dependencies: ['category'], views: ['category', 'data'], formats: ['project-json', 'recipe'], limitations: ['Workspace categories are presentation data. Functor endpoint checks do not certify composition preservation; existing condition editors and presets remain to migrate.'] },
  { id: 'ramification', sources: ['place_ramification_calculator.html', 'js/place_ramification_engine.js', 'js/place_ramification_calculator.js'], assets: ['fieldExtension', 'place', 'ramification'], fields: ['base', 'polynomial', 'generator', 'selection', 'places', 'certificates'], dependencies: ['fieldExtension'], views: ['ramification', 'data'], formats: ['project-json', 'recipe'], limitations: ['Local engine supports only its existing certified cases; unresolved places remain unresolved. Existing remote service and LMFDB selection UI remain to migrate.'] },
  { id: 'strand', sources: ['strand_diagram_calculator.html', 'js/strand_diagram_calculator.js', 'js/strand_math/index.js'], assets: ['strand', 'permutation', 'strandResult', 'linearCombination'], fields: ['rank', 'word', 'family', 'target', 'basis', 'coefficients'], dependencies: ['strand'], views: ['strand', 'data'], formats: ['project-json', 'recipe'], limitations: ['Native word evaluation reuses the existing engine. Full diagram editing, relation views, basis catalog UI, TikZ export and non-type-A interactions remain to migrate.'] },
];
export const typeFamily = Object.fromEntries(families.flatMap(f => f.assets.map(type => [type, f.id])));
export function buildCatalog(registry) {
  return { schema: 'math-workspace-asset-catalog', version: 1, fullParity: false, families: families.map(f => ({ ...f, migrationStatus: 'partial', constructors: [...registry.values()].filter(o => o.family === f.id && o.kind === 'constructor').map(({ run, ...op }) => op), workingOperations: [...registry.values()].filter(o => o.family === f.id && o.kind === 'operation').map(({ run, ...op }) => op) })) };
}
