// Generated by extract_legacy.py from js/matrix_calculator.js.
  const MAX_SIZE = 8;
  const TOL = 1e-10;
  const DISPLAY_TOL = 1e-12;
  const CHARPOLY_TIMEOUT_MS = 1500;
  const POLYNOMIAL_ACTION_TIMEOUT_MS = 1500;
  const POLYNOMIAL_ACTION_MAX_TERMS = 2000;
  const POLYNOMIAL_ACTION_MAX_EXPONENT = 64;
  const DEFAULT_FINITE_FIELD_PRIME = 7;
  const SMALL_PRIMES = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
    31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131, 137, 139, 149, 151, 157, 163, 167, 173,
    179, 181, 191, 193, 197, 199, 211, 223, 227, 229,
    233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
    283, 293
  ];
  class Complex {
    constructor(re = 0, im = 0) {
      this.re = Number(re) || 0;
      this.im = Number(im) || 0;
    }

    static from(value) {
      return value instanceof Complex ? value : new Complex(value, 0);
    }

    clone() { return new Complex(this.re, this.im); }
    add(other) { other = Complex.from(other); return new Complex(this.re + other.re, this.im + other.im); }
    sub(other) { other = Complex.from(other); return new Complex(this.re - other.re, this.im - other.im); }
    neg() { return new Complex(-this.re, -this.im); }
    scale(k) { return new Complex(this.re * k, this.im * k); }
    conj() { return new Complex(this.re, -this.im); }
    abs2() { return this.re * this.re + this.im * this.im; }
    abs() { return Math.hypot(this.re, this.im); }
    isZero(tol = TOL) { return this.abs2() <= tol * tol; }

    mul(other) {
      other = Complex.from(other);
      return new Complex(
        this.re * other.re - this.im * other.im,
        this.re * other.im + this.im * other.re
      );
    }

    div(other) {
      other = Complex.from(other);
      const den = other.abs2();
      if (den <= TOL * TOL) throw new Error('Division by zero.');
      return new Complex(
        (this.re * other.re + this.im * other.im) / den,
        (this.im * other.re - this.re * other.im) / den
      );
    }

    sqrt() {
      if (Math.abs(this.im) < DISPLAY_TOL && this.re >= 0) return new Complex(Math.sqrt(this.re), 0);
      const r = this.abs();
      const re = Math.sqrt(Math.max(0, (r + this.re) / 2));
      const imSign = this.im < 0 ? -1 : 1;
      const im = imSign * Math.sqrt(Math.max(0, (r - this.re) / 2));
      return new Complex(re, im);
    }
  }

  function copyMatrix(A) {
    return A.map((row) => row.map((z) => z.clone()));
  }

  function zeros(rows, cols) {
    return Array.from({ length: rows }, () => Array.from({ length: cols }, () => new Complex(0, 0)));
  }

  function identity(n) {
    const out = zeros(n, n);
    for (let i = 0; i < n; i++) out[i][i] = new Complex(1, 0);
    return out;
  }

  function matrixAdd(A, B) {
    return A.map((row, r) => row.map((z, c) => z.add(B[r][c])));
  }

  function matrixScale(A, k) {
    return A.map((row) => row.map((z) => z.scale(k)));
  }

  function matrixMultiply(A, B) {
    const rows = A.length;
    const inner = A[0]?.length || 0;
    const cols = B[0]?.length || 0;
    const out = zeros(rows, cols);
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        let sum = new Complex(0, 0);
        for (let k = 0; k < inner; k++) sum = sum.add(A[r][k].mul(B[k][c]));
        out[r][c] = sum;
      }
    }
    return out;
  }

  function adjoint(A) {
    const rows = A.length;
    const cols = A[0]?.length || 0;
    const out = zeros(cols, rows);
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) out[c][r] = A[r][c].conj();
    }
    return out;
  }

  function trace(A) {
    let sum = new Complex(0, 0);
    for (let i = 0; i < A.length; i++) sum = sum.add(A[i][i]);
    return sum;
  }

  function maxMatrixNorm(A) {
    let max = 0;
    for (const row of A) {
      let total = 0;
      for (const z of row) total += z.abs();
      max = Math.max(max, total);
    }
    return max;
  }

  function matrixRank(A) {
    return rref(A).rank;
  }

  function rref(A, tol = TOL) {
    const M = copyMatrix(A);
    const rows = M.length;
    const cols = M[0]?.length || 0;
    let pivotRow = 0;
    const pivots = [];
    for (let col = 0; col < cols && pivotRow < rows; col++) {
      let best = pivotRow;
      let bestAbs = M[best][col].abs();
      for (let r = pivotRow + 1; r < rows; r++) {
        const value = M[r][col].abs();
        if (value > bestAbs) {
          best = r;
          bestAbs = value;
        }
      }
      if (bestAbs <= tol) continue;
      if (best !== pivotRow) [M[pivotRow], M[best]] = [M[best], M[pivotRow]];
      const pivot = M[pivotRow][col];
      for (let c = col; c < cols; c++) M[pivotRow][c] = M[pivotRow][c].div(pivot);
      for (let r = 0; r < rows; r++) {
        if (r === pivotRow) continue;
        const factor = M[r][col];
        if (factor.isZero(tol)) continue;
        for (let c = col; c < cols; c++) M[r][c] = M[r][c].sub(factor.mul(M[pivotRow][c]));
      }
      pivots.push(col);
      pivotRow++;
    }
    return { matrix: M, pivots, rank: pivotRow };
  }

  function nullspace(A, tol = TOL) {
    const cols = A[0]?.length || 0;
    const { matrix: R, pivots } = rref(A, tol);
    const pivotSet = new Set(pivots);
    const freeCols = [];
    for (let c = 0; c < cols; c++) if (!pivotSet.has(c)) freeCols.push(c);
    return freeCols.map((freeCol) => {
      const v = Array.from({ length: cols }, () => new Complex(0, 0));
      v[freeCol] = new Complex(1, 0);
      for (let i = pivots.length - 1; i >= 0; i--) {
        const pivotCol = pivots[i];
        let sum = new Complex(0, 0);
        for (const c of freeCols) sum = sum.add(R[i][c].mul(v[c]));
        v[pivotCol] = sum.neg();
      }
      return normalizeVector(v);
    });
  }

  function nullity(A, tol = TOL) {
    const cols = A[0]?.length || 0;
    return cols - rref(A, tol).rank;
  }

  function matrixExp(A) {
    if (A.length !== (A[0]?.length || 0)) throw new Error('Matrix exponential requires a square matrix.');
    const n = A.length;
    const norm = maxMatrixNorm(A);
    const scalePower = norm > 0.5 ? Math.max(0, Math.ceil(Math.log2(norm / 0.5))) : 0;
    const B = matrixScale(A, 1 / Math.pow(2, scalePower));
    let result = identity(n);
    let term = identity(n);
    for (let k = 1; k <= 80; k++) {
      term = matrixScale(matrixMultiply(term, B), 1 / k);
      result = matrixAdd(result, term);
      if (maxMatrixNorm(term) < 1e-13) break;
    }
    for (let i = 0; i < scalePower; i++) result = matrixMultiply(result, result);
    return result;
  }

  function bruhatDecomposition(A) {
    const rows = A.length;
    const cols = A[0]?.length || 0;
    if (!rows || !cols) throw new Error('Bruhat decomposition requires a nonempty matrix.');
    const M = copyMatrix(A);
    const leftTransform = identity(rows);
    const rightTransform = identity(cols);
    const pivots = [];
    let maxRow = rows - 1;

    while (maxRow >= 0) {
      let pivotRow = -1;
      let pivotCol = -1;
      let pivotAbs = 0;

      for (let r = maxRow; r >= 0; r--) {
        for (let c = 0; c < cols; c++) {
          const value = M[r][c].abs();
          if (value > TOL) {
            pivotRow = r;
            pivotCol = c;
            pivotAbs = value;
            break;
          }
        }
        if (pivotRow >= 0) break;
      }
      if (pivotAbs <= TOL || pivotRow < 0 || pivotCol < 0) break;

      const pivot = M[pivotRow][pivotCol];
      for (let r = 0; r < pivotRow; r++) {
        if (M[r][pivotCol].isZero()) continue;
        const factor = M[r][pivotCol].div(pivot);
        for (let c = 0; c < cols; c++) M[r][c] = M[r][c].sub(factor.mul(M[pivotRow][c]));
        for (let c = 0; c < rows; c++) leftTransform[r][c] = leftTransform[r][c].sub(factor.mul(leftTransform[pivotRow][c]));
      }

      for (let c = pivotCol + 1; c < cols; c++) {
        if (M[pivotRow][c].isZero()) continue;
        const factor = M[pivotRow][c].div(pivot);
        for (let r = 0; r < rows; r++) M[r][c] = M[r][c].sub(M[r][pivotCol].mul(factor));
        for (let r = 0; r < cols; r++) rightTransform[r][c] = rightTransform[r][c].sub(rightTransform[r][pivotCol].mul(factor));
      }

      pivots.push({ row: pivotRow, col: pivotCol });
      maxRow = pivotRow - 1;
    }

    const W = zeros(rows, cols);
    const D = identity(cols);
    for (const { row, col } of pivots) {
      W[row][col] = new Complex(1, 0);
      D[col][col] = M[row][col].clone();
    }

    const B1 = inverseUpperTriangular(leftTransform);
    const B2 = matrixMultiply(D, inverseUpperTriangular(rightTransform));
    return { B1, W, B2, pivots, rank: pivots.length };
  }

  function inverseUpperTriangular(T) {
    const n = T.length;
    const X = zeros(n, n);
    for (let col = 0; col < n; col++) {
      for (let row = n - 1; row >= 0; row--) {
        let sum = row === col ? new Complex(1, 0) : new Complex(0, 0);
        for (let k = row + 1; k < n; k++) sum = sum.sub(T[row][k].mul(X[k][col]));
        if (T[row][row].isZero()) throw new Error('Upper triangular factor is singular.');
        X[row][col] = sum.div(T[row][row]);
      }
    }
    return X;
  }

  function qrDecomposition(A) {
    const m = A.length;
    const n = A[0]?.length || 0;
    const Qcols = [];
    const R = zeros(n, n);
    const dependent = [];
    for (let j = 0; j < n; j++) {
      let v = column(A, j);
      for (let i = 0; i < j; i++) {
        const qi = Qcols[i] || Array.from({ length: m }, () => new Complex(0, 0));
        const r = dotConj(qi, v);
        R[i][j] = r;
        v = v.map((z, row) => z.sub(qi[row].mul(r)));
      }
      const norm = vectorNorm(v);
      if (norm <= TOL) {
        Qcols[j] = Array.from({ length: m }, () => new Complex(0, 0));
        R[j][j] = new Complex(0, 0);
        dependent.push(j + 1);
      } else {
        Qcols[j] = v.map((z) => z.scale(1 / norm));
        R[j][j] = new Complex(norm, 0);
      }
    }
    const Q = zeros(m, n);
    for (let c = 0; c < n; c++) {
      for (let r = 0; r < m; r++) Q[r][c] = Qcols[c][r].clone();
    }
    return { Q, R, dependent };
  }

  function svdDecomposition(A) {
    const m = A.length;
    const n = A[0]?.length || 0;
    const gram = matrixMultiply(adjoint(A), A);
    const eig = hermitianEigenDecomposition(gram);
    const singularValues = eig.map((item) => Math.sqrt(Math.max(0, item.value)));
    const Vcols = eig.map((item) => item.vector);
    const Ucols = [];
    const rankTol = svdTolerance(singularValues);

    for (let i = 0; i < singularValues.length; i++) {
      if (singularValues[i] > rankTol) {
        Ucols.push(matrixVectorMultiply(A, Vcols[i]).map((z) => z.scale(1 / singularValues[i])));
      }
    }
    completeOrthonormalBasis(Ucols, m);

    const U = matrixFromColumns(Ucols.slice(0, m));
    const Sigma = zeros(m, n);
    for (let i = 0; i < Math.min(m, n); i++) Sigma[i][i] = new Complex(singularValues[i] || 0, 0);
    const V = matrixFromColumns(Vcols);
    return { U, Sigma, V, singularValues, rank: singularValues.filter((s) => s > rankTol).length };
  }

  function polarDecomposition(A) {
    const svd = svdDecomposition(A);
    const Vstar = adjoint(svd.V);
    const U = matrixMultiply(svd.U, matrixMultiply(rectangularPolarFactor(svd.singularValues, svd.U[0]?.length || 0, svd.V[0]?.length || 0), Vstar));
    const P = matrixMultiply(svd.V, matrixMultiply(squareDiagonal(svd.singularValues), Vstar));
    return { U, P, singularValues: svd.singularValues, rank: svd.rank };
  }

  function hermitianEigenDecomposition(H) {
    const n = H.length;
    const embedded = hermitianToRealSymmetric(H);
    const raw = jacobiSymmetric(embedded).sort((a, b) => b.value - a.value);
    const eigenpairs = [];
    const rankTol = 1e-7;
    for (const item of raw) {
      let candidate = complexFromRealPairVector(item.vector, n);
      candidate = orthogonalizeAgainst(candidate, eigenpairs.map((pair) => pair.vector));
      const norm = vectorNorm(candidate);
      if (norm <= rankTol) continue;
      candidate = candidate.map((z) => z.scale(1 / norm));
      const before = rankOfColumns(eigenpairs.map((pair) => pair.vector), rankTol);
      const after = rankOfColumns(eigenpairs.map((pair) => pair.vector).concat([candidate]), rankTol);
      if (after > before) eigenpairs.push({ value: item.value, vector: candidate });
      if (eigenpairs.length === n) break;
    }
    if (eigenpairs.length < n) completeHermitianEigenbasis(H, eigenpairs);
    return eigenpairs.slice(0, n).sort((a, b) => b.value - a.value);
  }

  function completeHermitianEigenbasis(H, eigenpairs) {
    const n = H.length;
    const existing = eigenpairs.map((pair) => pair.vector);
    completeOrthonormalBasis(existing, n);
    while (eigenpairs.length < n) {
      const vector = existing[eigenpairs.length];
      const Hv = matrixVectorMultiply(H, vector);
      const value = dotConj(vector, Hv).re;
      eigenpairs.push({ value, vector });
    }
  }

  function hermitianToRealSymmetric(H) {
    const n = H.length;
    const out = Array.from({ length: 2 * n }, () => Array.from({ length: 2 * n }, () => 0));
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        const z = H[r][c];
        out[r][c] = z.re;
        out[r][c + n] = -z.im;
        out[r + n][c] = z.im;
        out[r + n][c + n] = z.re;
      }
    }
    return out;
  }

  function jacobiSymmetric(A) {
    const n = A.length;
    const M = A.map((row) => row.slice());
    const V = Array.from({ length: n }, (_, r) => Array.from({ length: n }, (_, c) => r === c ? 1 : 0));
    const maxIter = Math.max(80, n * n * 40);
    for (let iter = 0; iter < maxIter; iter++) {
      let p = 0;
      let q = 1;
      let max = 0;
      for (let r = 0; r < n; r++) {
        for (let c = r + 1; c < n; c++) {
          const value = Math.abs(M[r][c]);
          if (value > max) {
            max = value;
            p = r;
            q = c;
          }
        }
      }
      if (max <= 1e-12) break;
      const tau = (M[q][q] - M[p][p]) / (2 * M[p][q]);
      const t = Math.sign(tau || 1) / (Math.abs(tau) + Math.sqrt(1 + tau * tau));
      const cs = 1 / Math.sqrt(1 + t * t);
      const sn = t * cs;
      rotateJacobi(M, V, p, q, cs, sn);
    }
    return Array.from({ length: n }, (_, i) => ({
      value: M[i][i],
      vector: V.map((row) => row[i])
    }));
  }

  function rotateJacobi(M, V, p, q, cs, sn) {
    const n = M.length;
    const app = M[p][p];
    const aqq = M[q][q];
    const apq = M[p][q];
    M[p][p] = cs * cs * app - 2 * cs * sn * apq + sn * sn * aqq;
    M[q][q] = sn * sn * app + 2 * cs * sn * apq + cs * cs * aqq;
    M[p][q] = 0;
    M[q][p] = 0;
    for (let k = 0; k < n; k++) {
      if (k === p || k === q) continue;
      const mkp = M[k][p];
      const mkq = M[k][q];
      M[k][p] = cs * mkp - sn * mkq;
      M[p][k] = M[k][p];
      M[k][q] = sn * mkp + cs * mkq;
      M[q][k] = M[k][q];
    }
    for (let k = 0; k < n; k++) {
      const vkp = V[k][p];
      const vkq = V[k][q];
      V[k][p] = cs * vkp - sn * vkq;
      V[k][q] = sn * vkp + cs * vkq;
    }
  }

  function complexFromRealPairVector(v, n) {
    return normalizeVector(Array.from({ length: n }, (_, i) => new Complex(v[i], v[i + n])));
  }

  function svdTolerance(singularValues) {
    const scale = singularValues[0] || 1;
    return Math.max(1e-10, scale * 1e-9);
  }

  function completeOrthonormalBasis(cols, size) {
    const candidates = [];
    for (let i = 0; i < size; i++) {
      const e = Array.from({ length: size }, (_, r) => new Complex(r === i ? 1 : 0, 0));
      candidates.push(e);
    }
    for (let i = 0; i < size; i++) {
      const e = Array.from({ length: size }, (_, r) => new Complex(0, r === i ? 1 : 0));
      candidates.push(e);
    }
    for (const candidate of candidates) {
      if (cols.length >= size) break;
      const v = orthogonalizeAgainst(candidate, cols);
      const norm = vectorNorm(v);
      if (norm > 1e-9) cols.push(v.map((z) => z.scale(1 / norm)));
    }
    while (cols.length < size) {
      const e = Array.from({ length: size }, (_, r) => new Complex(r === cols.length ? 1 : 0, 0));
      cols.push(e);
    }
    return cols;
  }

  function orthogonalizeAgainst(vector, basis) {
    let v = vector.map((z) => z.clone());
    for (const q of basis) {
      const coeff = dotConj(q, v);
      v = v.map((z, i) => z.sub(q[i].mul(coeff)));
    }
    return v;
  }

  function rectangularPolarFactor(values, rows, cols) {
    const out = zeros(rows, cols);
    const tol = svdTolerance(values);
    for (let i = 0; i < Math.min(rows, cols, values.length); i++) {
      out[i][i] = new Complex(values[i] > tol ? 1 : 0, 0);
    }
    return out;
  }

  function squareDiagonal(values) {
    const out = zeros(values.length, values.length);
    for (let i = 0; i < values.length; i++) out[i][i] = new Complex(values[i] || 0, 0);
    return out;
  }

  function column(A, c) {
    return A.map((row) => row[c].clone());
  }

  function dotConj(u, v) {
    let sum = new Complex(0, 0);
    for (let i = 0; i < u.length; i++) sum = sum.add(u[i].conj().mul(v[i]));
    return sum;
  }

  function vectorNorm(v) {
    return Math.sqrt(v.reduce((sum, z) => sum + z.abs2(), 0));
  }

  function jordanDecomposition(A) {
    if (A.length !== (A[0]?.length || 0)) throw new Error('Jordan decomposition requires a square matrix.');
    const n = A.length;
    const groups = jordanEigenvalueGroups(A);
    const J = zeros(n, n);
    const pColumns = [];
    const summaries = [];
    let offset = 0;
    let canBuildP = true;

    for (const group of groups) {
      const lambda = cleanComplex(group.lambda, 1e-9);
      const N = subtractScalarIdentity(A, lambda);
      const structure = jordanStructureForEigenvalue(A, N, group.multiplicity);
      const blockSizes = structure.blockSizes;
      const basesByPower = canBuildP
        ? nullspaceBasesByPower(N, Math.max(...blockSizes), structure.tol)
        : [];

      summaries.push(`${formatComplex(lambda)}: alg ${group.multiplicity}, eig ${structure.nullities[1] || 0}, blocks ${blockSizes.join('+')}`);

      for (const size of blockSizes) {
        for (let i = 0; i < size; i++) {
          J[offset + i][offset + i] = lambda.clone();
          if (i < size - 1) J[offset + i][offset + i + 1] = new Complex(1, 0);
        }
        if (canBuildP) {
          const chain = chooseJordanChain(N, size, pColumns, basesByPower, structure.tol);
          if (chain) pColumns.push(...chain);
          else canBuildP = false;
        }
        offset += size;
      }
    }

    const blocks = [];
    let formula = 'Jordan form J';
    if (canBuildP && pColumns.length === n) {
      const P = matrixFromColumns(pColumns);
      const residual = jordanResidual(A, P, J);
      const scale = Math.max(1, maxMatrixNorm(A), maxMatrixNorm(P), maxMatrixNorm(J));
      if (matrixRank(P) === n && residual <= 1e-6 * scale * scale) {
        blocks.push({ title: 'P', matrix: P });
        formula = 'A = P J P^{-1}';
      }
    }
    blocks.push({ title: 'J', matrix: J });

    const pNote = blocks.length > 1
      ? 'P was constructed from eigenvectors and generalized eigenvectors.'
      : 'Only J is shown because a stable generalized eigenvector basis P could not be constructed numerically.';
    return {
      formula,
      blocks,
      note: `Eigenvalues: ${summaries.join('; ')}. ${pNote} Numerical Jordan data is tolerance-sensitive for repeated or nearby eigenvalues.`
    };
  }

  function jordanEigenvalueGroups(A) {
    const triangular = triangularEigenvalues(A);
    const roots = triangular || polynomialRoots(characteristicPolynomial(A));
    return clusterEigenvalues(roots).sort((a, b) => {
      if (Math.abs(a.lambda.re - b.lambda.re) > 1e-9) return a.lambda.re - b.lambda.re;
      return a.lambda.im - b.lambda.im;
    });
  }

  function triangularEigenvalues(A) {
    const n = A.length;
    let upper = true;
    let lower = true;
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        if (r > c && !A[r][c].isZero(1e-10)) upper = false;
        if (r < c && !A[r][c].isZero(1e-10)) lower = false;
      }
    }
    if (!upper && !lower) return null;
    return A.map((row, i) => row[i].clone());
  }

  function characteristicPolynomial(A, guard = null) {
    const n = A.length;
    const coeffs = [new Complex(1, 0)];
    let B = identity(n);
    for (let k = 1; k <= n; k++) {
      checkDeadline(guard);
      const AB = matrixMultiply(A, B);
      const coeff = trace(AB).scale(-1 / k);
      coeffs.push(cleanComplex(coeff, 1e-12));
      B = copyMatrix(AB);
      for (let i = 0; i < n; i++) B[i][i] = B[i][i].add(coeff);
    }
    return coeffs;
  }

  function checkDeadline(guard) {
    if (guard && performanceNow() > guard.expires) throw new Error('CHARPOLY_TIMEOUT');
  }

  function performanceNow() {
    return (typeof performance !== 'undefined' && performance.now) ? performance.now() : Date.now();
  }

  function polynomialRoots(coeffs, guard = null) {
    const degree = coeffs.length - 1;
    if (degree < 1) return [];
    checkDeadline(guard);
    const leading = coeffs[0];
    const poly = leading.sub(1).abs() <= DISPLAY_TOL
      ? coeffs.map((z) => z.clone())
      : coeffs.map((z) => z.div(leading));
    if (degree === 1) return [poly[1].neg()];
    if (degree === 2) return quadraticRoots(poly);

    const radius = 1 + Math.max(...poly.slice(1).map((z) => z.abs()));
    let roots = Array.from({ length: degree }, (_, i) => {
      const theta = (2 * Math.PI * (i + 0.37)) / degree;
      return new Complex(radius * Math.cos(theta), radius * Math.sin(theta));
    });

    for (let iter = 0; iter < 220; iter++) {
      checkDeadline(guard);
      let maxDelta = 0;
      roots = roots.map((root, i) => {
        let denom = new Complex(1, 0);
        for (let j = 0; j < roots.length; j++) {
          if (i !== j) denom = denom.mul(root.sub(roots[j]));
        }
        if (denom.abs() <= 1e-14) denom = new Complex(1e-14, 1e-14);
        const delta = polynomialEval(poly, root).div(denom);
        maxDelta = Math.max(maxDelta, delta.abs());
        return root.sub(delta);
      });
      if (maxDelta <= 1e-12) break;
    }
    return roots.map((z) => cleanComplex(z, 1e-8));
  }

  function quadraticRoots(coeffs) {
    const b = coeffs[1];
    const c = coeffs[2];
    const disc = b.mul(b).sub(c.scale(4)).sqrt();
    return [b.neg().add(disc).scale(0.5), b.neg().sub(disc).scale(0.5)].map((z) => cleanComplex(z, 1e-10));
  }

  function polynomialEval(coeffs, x) {
    let value = coeffs[0].clone();
    for (let i = 1; i < coeffs.length; i++) value = value.mul(x).add(coeffs[i]);
    return value;
  }

  function clusterEigenvalues(values) {
    const clusters = [];
    const sorted = values.map((z) => z.clone()).sort((a, b) => {
      if (Math.abs(a.re - b.re) > 1e-9) return a.re - b.re;
      return a.im - b.im;
    });
    for (const root of sorted) {
      const scale = Math.max(1, root.abs());
      let match = null;
      let bestDistance = Infinity;
      for (const cluster of clusters) {
        const distance = root.sub(cluster.lambda).abs();
        const tol = 1e-5 * Math.max(scale, 1, cluster.lambda.abs());
        if (distance <= tol && distance < bestDistance) {
          match = cluster;
          bestDistance = distance;
        }
      }
      if (!match) {
        clusters.push({ lambda: root.clone(), sum: root.clone(), multiplicity: 1 });
      } else {
        match.sum = match.sum.add(root);
        match.multiplicity++;
        match.lambda = match.sum.scale(1 / match.multiplicity);
      }
    }
    return clusters.map((cluster) => ({
      lambda: cleanComplex(cluster.lambda, 1e-8),
      multiplicity: cluster.multiplicity
    }));
  }

  function jordanStructureForEigenvalue(A, N, multiplicity) {
    const scale = Math.max(1, maxMatrixNorm(A), maxMatrixNorm(N));
    const tolerances = [1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5].map((tol) => tol * scale);
    let best = null;
    for (const tol of tolerances) {
      const nullities = jordanNullities(N, multiplicity, tol).map((d) => Math.min(d, multiplicity));
      const good = nullities[multiplicity] === multiplicity && nullities[1] > 0 && hasJordanNullityShape(nullities);
      const score = (nullities[multiplicity] || 0) * 100 + (nullities[1] || 0);
      if (!best || score > best.score) {
        best = { tol, nullities, score };
      }
      if (good) {
        best = { tol, nullities, score };
        break;
      }
    }
    const repaired = repairJordanNullities(best.nullities, multiplicity);
    return {
      tol: best.tol,
      nullities: repaired,
      blockSizes: blockSizesFromNullities(repaired, multiplicity)
    };
  }

  function jordanNullities(N, multiplicity, tol) {
    const n = N.length;
    const values = [0];
    let power = identity(n);
    for (let k = 1; k <= multiplicity; k++) {
      power = matrixMultiply(power, N);
      values.push(nullity(power, tol));
    }
    return values;
  }

  function hasJordanNullityShape(nullities) {
    let previousIncrement = Infinity;
    for (let k = 1; k < nullities.length; k++) {
      const increment = nullities[k] - nullities[k - 1];
      if (increment < 0 || increment > previousIncrement) return false;
      previousIncrement = increment;
    }
    return true;
  }

  function repairJordanNullities(nullities, multiplicity) {
    const repaired = [0];
    for (let k = 1; k <= multiplicity; k++) {
      const value = Math.round(nullities[k] || 0);
      repaired[k] = Math.max(repaired[k - 1], Math.min(multiplicity, value));
    }
    repaired[multiplicity] = multiplicity;
    return repaired;
  }

  function blockSizesFromNullities(nullities, multiplicity) {
    const atLeast = Array.from({ length: multiplicity + 2 }, () => 0);
    for (let k = 1; k <= multiplicity; k++) {
      atLeast[k] = Math.max(0, nullities[k] - nullities[k - 1]);
    }
    for (let k = 2; k <= multiplicity; k++) atLeast[k] = Math.min(atLeast[k], atLeast[k - 1]);
    let total = atLeast.reduce((sum, value) => sum + value, 0);
    while (total < multiplicity) {
      atLeast[1]++;
      total++;
    }
    for (let k = multiplicity; total > multiplicity && k >= 1; k--) {
      const floor = atLeast[k + 1] || 0;
      const drop = Math.min(atLeast[k] - floor, total - multiplicity);
      if (drop > 0) {
        atLeast[k] -= drop;
        total -= drop;
      }
    }

    const sizes = [];
    for (let k = multiplicity; k >= 1; k--) {
      const exact = Math.max(0, atLeast[k] - (atLeast[k + 1] || 0));
      for (let i = 0; i < exact; i++) sizes.push(k);
    }
    return sizes.length ? sizes : [multiplicity];
  }

  function nullspaceBasesByPower(N, maxPower, tol) {
    const bases = [[]];
    let power = identity(N.length);
    for (let k = 1; k <= maxPower; k++) {
      power = matrixMultiply(power, N);
      bases[k] = nullspace(power, tol);
    }
    return bases;
  }

  function chooseJordanChain(N, size, existingColumns, basesByPower, tol) {
    const basis = basesByPower[size] || [];
    const before = rankOfColumns(existingColumns, tol);
    for (const candidate of jordanChainCandidates(basis)) {
      const chain = jordanChainFromTop(N, candidate, size);
      if (chain.some((v) => vectorNorm(v) <= tol)) continue;
      const after = rankOfColumns(existingColumns.concat(chain), tol);
      if (after >= before + size) return scaleChainForDisplay(chain);
    }
    return null;
  }

  function jordanChainCandidates(basis) {
    const candidates = basis.map((v) => v.map((z) => z.clone()));
    for (let i = 0; i < basis.length; i++) {
      for (let j = i + 1; j < basis.length; j++) {
        candidates.push(addVectors(basis[i], basis[j]));
        candidates.push(addVectors(basis[i], basis[j].map((z) => z.mul(new Complex(0, 1)))));
      }
    }
    return candidates;
  }

  function jordanChainFromTop(N, top, size) {
    const chain = [top.map((z) => z.clone())];
    let current = top.map((z) => z.clone());
    for (let k = 1; k < size; k++) {
      current = matrixVectorMultiply(N, current);
      chain.unshift(current);
    }
    return chain;
  }

  function scaleChainForDisplay(chain) {
    const top = chain[chain.length - 1];
    const norm = vectorNorm(top);
    if (norm <= TOL) return chain;
    return chain.map((v) => v.map((z) => z.scale(1 / norm)));
  }

  function jordanResidual(A, P, J) {
    const AP = matrixMultiply(A, P);
    const PJ = matrixMultiply(P, J);
    return maxMatrixNorm(matrixAdd(AP, matrixScale(PJ, -1)));
  }

  function subtractScalarIdentity(A, scalar) {
    const out = copyMatrix(A);
    for (let i = 0; i < out.length; i++) out[i][i] = out[i][i].sub(scalar);
    return out;
  }

  function matrixVectorMultiply(A, v) {
    return A.map((row) => row.reduce((sum, z, c) => sum.add(z.mul(v[c])), new Complex(0, 0)));
  }

  function addVectors(a, b) {
    return a.map((z, i) => z.add(b[i]));
  }

  function rankOfColumns(cols, tol) {
    if (!cols.length) return 0;
    return rref(matrixFromColumns(cols), tol).rank;
  }

  function cleanComplex(z, tol = DISPLAY_TOL) {
    z = Complex.from(z);
    return new Complex(Math.abs(z.re) < tol ? 0 : z.re, Math.abs(z.im) < tol ? 0 : z.im);
  }

  function normalizeVector(v) {
    const norm = vectorNorm(v);
    if (norm <= TOL) return v;
    return v.map((z) => z.scale(1 / norm));
  }

  function matrixFromColumns(cols) {
    const rows = cols[0].length;
    const out = zeros(rows, cols.length);
    for (let c = 0; c < cols.length; c++) {
      for (let r = 0; r < rows; r++) out[r][c] = cols[c][r].clone();
    }
    return out;
  }

  function formatReal(value, digits = 8) {
    if (Math.abs(value) < DISPLAY_TOL) value = 0;
    const nearInteger = Math.round(value);
    if (Math.abs(value - nearInteger) < DISPLAY_TOL) return String(nearInteger);
    return Number(value.toPrecision(digits)).toString();
  }

  function formatComplex(z, digits = 8) {
    z = Complex.from(z);
    const re = Math.abs(z.re) < DISPLAY_TOL ? 0 : z.re;
    const im = Math.abs(z.im) < DISPLAY_TOL ? 0 : z.im;
    if (im === 0) return formatReal(re, digits);
    if (re === 0) {
      if (Math.abs(im - 1) < DISPLAY_TOL) return 'i';
      if (Math.abs(im + 1) < DISPLAY_TOL) return '-i';
      return `${formatReal(im, digits)}i`;
    }
    const sign = im < 0 ? '-' : '+';
    const absIm = Math.abs(im);
    const imag = Math.abs(absIm - 1) < DISPLAY_TOL ? 'i' : `${formatReal(absIm, digits)}i`;
    return `${formatReal(re, digits)} ${sign} ${imag}`;
  }
export { Complex, qrDecomposition, svdDecomposition, polarDecomposition, matrixExp, bruhatDecomposition, jordanDecomposition };
