// Generated by extract_legacy.py; source functions remain byte-for-byte equivalent.
// Source: js/double_young_diagram.js. Existing limits and numerical caveats apply.
    const MAX_EXACT_CELLS = 25;
    const MAX_STABLE_BOXES_TYPE_A = 15;
    const MAX_STABLE_BOXES_CLASSICAL = 12;
    const MAX_WEYL_ORBIT = 60000;
    const MAX_SUPPORT_BOX = 26000;
    const MAX_PRODUCT_WEIGHT_PAIRS = 90000;
    const MAX_DOMINANT_CANDIDATES = 3000;
    const MAX_EXCEPTIONAL_SUBDIAGRAM_CANDIDATES = 3000;
    const MAX_EXCEPTIONAL_TYPE_A_SOURCE_BOXES = 12;
    const MAX_KOSTANT_STEPS = 220000;
    const MAX_FREUDENTHAL_WEIGHTS = 20000;
    const MAX_NORM_BOUND_CANDIDATES = 12000;
    const MAX_SLICE_CHARACTER_CANDIDATES = 5000;
    const MAX_SLICE_PROJECTION_CANDIDATES = 3000000;
    const SLICE_PROJECTION_BOX_WARNING_CANDIDATES = 600000;
    const MAX_SLICE_PROJECTION_BOX_CANDIDATES = 6000000;
    const SLICE_FREUDENTHAL_EPS = 1e-7;
    const MAX_KOSTKA_STEPS = 250000;
    const MAX_KOSTKA_TABLEAUX = 3000;
    const MAX_KRONECKER_BOXES = 12;
    const MAX_PLETHYSM_BOXES = 12;
    const MAX_POWER_SUM_TERMS = 6000;
    const MAX_SCHUR_FUNCTOR_CHAR_TERMS = 16000;
    const MAX_SCHUR_FUNCTOR_DECOMP_TERMS = 800;
    const MAX_GRASSMANNIAN_TERMS = 1200;
    const MAX_CHERN_DETERMINANT_SIZE = 7;
    const MAX_CHERN_POLY_TERMS = 4000;
    const MAX_OPEN_CHART_CARDS = 3;
    const SYMPOLY_VARIABLE_MAX = 18 * 18;
    const SYMPOLY_POLYNOMIAL_TERM_LIMIT = 1000000;
    const SYMPOLY_EXPANSION_PARTITION_LIMIT = 500000;
    const SYMPOLY_PRODUCT_PARTITION_LIMIT = 50000;
    const SYMPOLY_BASIS_CONVERSION_LIMIT = 180;
    const SYMPOLY_LINEAR_MODE_PARTITION_LIMIT = 180;
    const SYMPOLY_SCHUR_DETERMINANT_LIMIT = 8;
    const SYMPOLY_PLETHYSM_BOX_LIMIT = 50;
    const SYMPOLY_PRODUCT_TIME_LIMIT_MS = 3000;
    const SYMPOLY_ORDER = ['m', 'p', 'e', 'h', 's'];
    let sympolyComputationDeadline = 0;
    let sympolyComputationCheckCounter = 0;
    let sympolyComputationStage = '';
    const sympolyPartitionCountCache = new Map();
    const sympolyGroupProfileCache = new Map();
    const sympolyRowTransitionCache = new Map();
    const sympolyPowerTransitionCache = new Map();
    const sympolySchurGeneratorCache = new Map();
    const key = (v) => v.join(',');
    const add = (a,b) => a.map((x,i) => x + b[i]);
    const sub = (a,b) => a.map((x,i) => x - b[i]);
    const scale = (a,k) => a.map(x => x * k);
    const dot = (a,b) => a.reduce((s,x,i) => s + x*b[i], 0);
const symmetricCharacterMemo = new Map();
    function trimPartition(p) {
      const out = [];
      for (const x of p) {
        const v = Math.max(0, Math.floor(Number(x) || 0));
        if (v > 0) out.push(v);
      }
      while (out.length && out[out.length - 1] === 0) out.pop();
      return out;
    }

    function partitionToString(p) {
      const q = trimPartition(p);
      return q.length ? '(' + q.join(',') + ')' : '∅';
    }

    function partitionKey(p) { return trimPartition(p).join(','); }

    function sizeOf(p) { return trimPartition(p).reduce((a,b) => a + b, 0); }

    function containsPartition(outer, inner) {
      const n = Math.max(outer.length, inner.length);
      for (let i = 0; i < n; i++) if ((outer[i] || 0) < (inner[i] || 0)) return false;
      return true;
    }

    function conjugatePartition(p) {
      p = trimPartition(p);
      const max = p[0] || 0;
      const out = [];
      for (let c = 1; c <= max; c++) out.push(p.filter(r => r >= c).length);
      return out;
    }

    function partitionsOf(total, maxPart = total, maxLen = total) {
      const out = [];
      function rec(rem, top, acc) {
        if (rem === 0) { out.push(acc.slice()); return; }
        if (acc.length >= maxLen) return;
        const m = Math.min(top, rem, maxPart);
        for (let x = m; x >= 1; x--) { acc.push(x); rec(rem - x, x, acc); acc.pop(); }
      }
      if (total === 0) return [[]];
      rec(total, maxPart, []);
      return out;
    }

    function skewCells(outer, inner) {
      const cells = [];
      for (let r = 0; r < outer.length; r++) {
        const start = inner[r] || 0;
        for (let c = start; c < outer[r]; c++) cells.push([r,c]);
      }
      return cells;
    }

    function lrCoefficient(lambda, mu, nu) {
      lambda = trimPartition(lambda); mu = trimPartition(mu); nu = trimPartition(nu);
      if (!containsPartition(nu, lambda)) return 0;
      if (sizeOf(nu) !== sizeOf(lambda) + sizeOf(mu)) return 0;
      const total = sizeOf(mu);
      if (total === 0) return partitionKey(lambda) === partitionKey(nu) ? 1 : 0;
      if (total > MAX_EXACT_CELLS) throw new Error(`Exact LR computation capped at ${MAX_EXACT_CELLS} skew boxes.`);
      const k = mu.length;
      const cells = skewCells(nu, lambda).sort((a,b) => (a[0] - b[0]) || (b[1] - a[1]));
      const grid = new Map();
      const remaining = mu.slice();
      const prefixCounts = Array(k).fill(0);
      let count = 0;
      const get = (r,c) => grid.get(r + ',' + c);
      function ballotOK() { for (let i=0;i<k-1;i++) if (prefixCounts[i] < prefixCounts[i+1]) return false; return true; }
      function rec(index) {
        if (index === cells.length) { count++; return; }
        const [r,c] = cells[index];
        const right = get(r, c + 1);
        const above = get(r - 1, c);
        for (let value = 1; value <= k; value++) {
          if (remaining[value - 1] <= 0) continue;
          if (right !== undefined && value > right) continue;
          if (above !== undefined && value <= above) continue;
          remaining[value - 1]--; prefixCounts[value - 1]++;
          if (ballotOK()) { grid.set(r + ',' + c, value); rec(index + 1); grid.delete(r + ',' + c); }
          prefixCounts[value - 1]--; remaining[value - 1]++;
        }
      }
      rec(0);
      return count;
    }

    function stableClassicalCoefficient(lambda, mu, nu) {
      lambda = trimPartition(lambda); mu = trimPartition(mu); nu = trimPartition(nu);
      const L = sizeOf(lambda), M = sizeOf(mu), N = sizeOf(nu);
      const a = (L + M - N) / 2, b = (L + N - M) / 2, c = (M + N - L) / 2;
      if (![a,b,c].every(x => Number.isInteger(x) && x >= 0)) return 0;
      const work = a + b + c;
      if (work > MAX_EXACT_CELLS) throw new Error(`Classical coefficient capped at total auxiliary size ${MAX_EXACT_CELLS}.`);
      let total = 0;
      for (const alpha of partitionsOf(a)) for (const beta of partitionsOf(b)) {
        const first = lrCoefficient(alpha, beta, lambda);
        if (!first) continue;
        for (const gamma of partitionsOf(c)) {
          const second = lrCoefficient(alpha, gamma, mu);
          if (!second) continue;
          const third = lrCoefficient(beta, gamma, nu);
          if (third) total += first * second * third;
        }
      }
      return total;
    }

    function decomposeTypeAStable(lambda, mu) {
      const total = sizeOf(lambda) + sizeOf(mu);
      if (total > MAX_STABLE_BOXES_TYPE_A) throw new Error(`Stable type A decomposition capped at ${MAX_STABLE_BOXES_TYPE_A} total boxes.`);
      const terms = [];
      for (const nu of partitionsOf(total, total, total || 1)) {
        if (!containsPartition(nu, lambda)) continue;
        const c = lrCoefficient(lambda, mu, nu);
        if (c) terms.push({ labels: null, nu, coefficient: c, dimension: null });
      }
      return terms;
    }

    function decomposeClassicalStable(lambda, mu) {
      const total = sizeOf(lambda) + sizeOf(mu);
      if (total > MAX_STABLE_BOXES_CLASSICAL) throw new Error(`Classical stable decomposition capped at ${MAX_STABLE_BOXES_CLASSICAL} total boxes.`);
      const terms = [];
      for (let s = total; s >= 0; s -= 2) for (const nu of partitionsOf(s, s, s || 1)) {
        const c = stableClassicalCoefficient(lambda, mu, nu);
        if (c) terms.push({ labels: null, nu, coefficient: c, dimension: null });
      }
      return terms;
    }

    function isExceptionalType(type) { return ['E6','E7','E8','F4','G2'].includes(type); }

    function cartanMatrix(type, rank) {
      const make = (n, cb) => Array.from({length:n}, (_,i) => Array.from({length:n}, (_,j) => cb(i,j)));
      if (type === 'A') return make(rank, (i,j) => i === j ? 2 : Math.abs(i-j) === 1 ? -1 : 0);
      if (type === 'B') {
        const C = make(rank, (i,j) => i === j ? 2 : Math.abs(i-j) === 1 ? -1 : 0);
        if (rank >= 2) { C[rank-2][rank-1] = -2; C[rank-1][rank-2] = -1; }
        return C;
      }
      if (type === 'C') {
        const C = make(rank, (i,j) => i === j ? 2 : Math.abs(i-j) === 1 ? -1 : 0);
        if (rank >= 2) { C[rank-2][rank-1] = -1; C[rank-1][rank-2] = -2; }
        return C;
      }
      if (type === 'D') {
        const C = make(rank, (i,j) => i === j ? 2 : 0);
        for (let i=0;i<rank-2;i++) { C[i][i+1] = -1; C[i+1][i] = -1; }
        if (rank >= 3) { C[rank-3][rank-1] = -1; C[rank-1][rank-3] = -1; }
        return C;
      }
      if (type === 'G2') return [[2,-1],[-3,2]];
      if (type === 'F4') return [[2,-1,0,0],[-1,2,-2,0],[0,-1,2,-1],[0,0,-1,2]];
      if (type === 'E6') {
        const C = make(6, (i,j) => i === j ? 2 : 0);
        [[0,1],[1,2],[2,3],[3,4],[2,5]].forEach(([a,b]) => { C[a][b] = -1; C[b][a] = -1; });
        return C;
      }
      if (type === 'E7') {
        const C = make(7, (i,j) => i === j ? 2 : 0);
        [[0,1],[1,2],[2,3],[3,4],[4,5],[2,6]].forEach(([a,b]) => { C[a][b] = -1; C[b][a] = -1; });
        return C;
      }
      if (type === 'E8') {
        const C = make(8, (i,j) => i === j ? 2 : 0);
        [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[2,7]].forEach(([a,b]) => { C[a][b] = -1; C[b][a] = -1; });
        return C;
      }
      throw new Error('Unsupported Lie type.');
    }

    function transpose(M) { return M[0].map((_,j) => M.map(row => row[j])); }

    function simpleToDynkin(simple, C) {
      const n = C.length;
      return Array.from({length:n}, (_,j) => simple.reduce((s,x,i) => s + x*C[i][j], 0));
    }

    function solveLinear(A, b) {
      const n = A.length;
      const M = A.map((row,i) => row.map(Number).concat([Number(b[i])]));
      for (let col=0; col<n; col++) {
        let pivot = col;
        for (let r=col+1; r<n; r++) if (Math.abs(M[r][col]) > Math.abs(M[pivot][col])) pivot = r;
        if (Math.abs(M[pivot][col]) < 1e-10) return null;
        [M[col], M[pivot]] = [M[pivot], M[col]];
        const div = M[col][col];
        for (let j=col; j<=n; j++) M[col][j] /= div;
        for (let r=0; r<n; r++) if (r !== col) {
          const f = M[r][col];
          for (let j=col; j<=n; j++) M[r][j] -= f*M[col][j];
        }
      }
      return M.map(row => row[n]);
    }

    function dynkinToSimple(v, C) {
      const sol = solveLinear(transpose(C), v);
      if (!sol) return null;
      const rounded = sol.map(x => Math.round(x));
      for (let i=0;i<sol.length;i++) if (Math.abs(sol[i] - rounded[i]) > 1e-7) return null;
      return rounded;
    }

    function isNonnegativeIntVector(v) { return !!v && v.every(x => Number.isInteger(x) && x >= 0); }

    function isDominantDynkin(labels) { return !!labels && labels.every(x => Number.isInteger(x) && x >= 0); }

    function positiveRoots(C) {
      const n = C.length;
      const roots = new Map();
      const queue = [];
      for (let i=0;i<n;i++) { const e = Array(n).fill(0); e[i] = 1; roots.set(key(e), e); queue.push(e); }
      while (queue.length) {
        const r = queue.pop();
        for (let i=0;i<n;i++) {
          const bracket = r.reduce((s,x,j) => s + x*C[j][i], 0);
          const nr = r.slice(); nr[i] -= bracket;
          if (nr.every(x => x >= 0) && !roots.has(key(nr))) { roots.set(key(nr), nr); queue.push(nr); }
        }
      }
      return Array.from(roots.values()).sort((a,b) => a.reduce((s,x)=>s+x,0) - b.reduce((s,x)=>s+x,0));
    }

    function reflectDynkin(v, i, C) {
      const ai = v[i];
      return v.map((x,j) => x - ai*C[i][j]);
    }

    function weylOrbitSigned(v, C, cap = MAX_WEYL_ORBIT) {
      const seen = new Map();
      const q = [{ wt: v.slice(), sign: 1 }];
      seen.set(key(v), { wt: v.slice(), sign: 1 });
      for (let head=0; head<q.length; head++) {
        const cur = q[head];
        for (let i=0;i<C.length;i++) {
          const nw = reflectDynkin(cur.wt, i, C);
          const k = key(nw);
          if (!seen.has(k)) {
            const item = { wt: nw, sign: -cur.sign };
            seen.set(k, item); q.push(item);
            if (seen.size > cap) throw new Error(`Weyl orbit has more than ${cap} weights; lower the rank or use stable mode.`);
          }
        }
      }
      return Array.from(seen.values());
    }

    function diagramToDynkinLabels(rows, rank) {
      const r = Array.from({length:rank}, (_,i) => trimPartition(rows)[i] || 0);
      return Array.from({length:rank}, (_,i) => r[i] - (r[i+1] || 0));
    }

    function dynkinLabelsToDiagram(labels) {
      const rows = Array(labels.length).fill(0);
      for (let i=labels.length-1;i>=0;i--) rows[i] = labels[i] + (rows[i+1] || 0);
      return trimPartition(rows);
    }

    function gcdBI(a,b) { a = a < 0n ? -a : a; b = b < 0n ? -b : b; while (b) [a,b] = [b, a%b]; return a; }

    function normalizeFrac(fr) {
      let [a,b] = fr;
      if (b < 0n) { a = -a; b = -b; }
      const g = gcdBI(a, b);
      return [a / g, b / g];
    }

    function mulFrac(fr, num, den) {
      let [a,b] = normalizeFrac(fr);
      let c = BigInt(num), d = BigInt(den);
      [c,d] = normalizeFrac([c,d]);
      let g = gcdBI(c, b); c /= g; b /= g;
      g = gcdBI(a, d); a /= g; d /= g;
      return normalizeFrac([a*c, b*d]);
    }

    function weylDimensionFrac(labels, C) {
      const coroots = positiveRoots(transpose(C));
      let fr = [1n, 1n];
      for (const cr of coroots) {
        const num = cr.reduce((s,x,i) => s + x*(labels[i] + 1), 0);
        const den = cr.reduce((s,x) => s + x, 0);
        fr = mulFrac(fr, num, den);
      }
      return normalizeFrac(fr);
    }

    function weylDimensionBigInt(labels, C) {
      const fr = weylDimensionFrac(labels, C);
      if (fr[1] === 1n) return fr[0];
      if (fr[0] % fr[1] === 0n) return fr[0] / fr[1];
      throw new Error(`Weyl dimension did not reduce to an integer: ${fr[0].toString()}/${fr[1].toString()}`);
    }

    function weylDimension(labels, C) {
      try { return weylDimensionBigInt(labels, C).toString(); }
      catch (err) {
        const fr = weylDimensionFrac(labels, C);
        return `${fr[0].toString()}/${fr[1].toString()}`;
      }
    }

    function makeWeylContext(type, rank) {
      const C = cartanMatrix(type, rank);
      const rootsSimple = positiveRoots(C);
      const rho = Array(C.length).fill(1);
      const partitionMemo = new Map();
      const orbitMemo = new Map();
      const weightMultMemo = new Map();
      let kostantSteps = 0;
      function orbit(v) {
        const k = key(v);
        if (!orbitMemo.has(k)) orbitMemo.set(k, weylOrbitSigned(v, C));
        return orbitMemo.get(k);
      }
      function partitionFunction(gammaDyn) {
        const gamma = dynkinToSimple(gammaDyn, C);
        if (!isNonnegativeIntVector(gamma)) return 0;
        const k0 = key(gamma);
        if (partitionMemo.has(k0)) return partitionMemo.get(k0);
        const memo = new Map();
        function rec(index, rem) {
          if (++kostantSteps > MAX_KOSTANT_STEPS) throw new Error(`Kostant partition recursion exceeded ${MAX_KOSTANT_STEPS} steps. The candidate list is small, but this coefficient is still too expensive in the browser; try smaller diagrams or use Sage/LiE for this exceptional case.`);
          if (rem.some(x => x < 0)) return 0;
          if (index === rootsSimple.length) return rem.every(x => x === 0) ? 1 : 0;
          const mk = index + '|' + key(rem);
          if (memo.has(mk)) return memo.get(mk);
          const root = rootsSimple[index];
          let total = 0;
          let next = rem.slice();
          while (next.every(x => x >= 0)) {
            total += rec(index + 1, next);
            next = next.map((x,i) => x - root[i]);
          }
          memo.set(mk, total);
          return total;
        }
        const val = rec(0, gamma);
        partitionMemo.set(k0, val);
        return val;
      }
      function weightMultiplicity(highest, wt) {
        const mk = key(highest) + '::' + key(wt);
        if (weightMultMemo.has(mk)) return weightMultMemo.get(mk);
        // Fast dominance/root-lattice rejection: every weight of V^highest is
        // highest minus a nonnegative integral sum of simple roots.  This avoids
        // thousands of unnecessary Kostant sums in tensor-product calculations.
        const deltaFromHighest = dynkinToSimple(sub(highest, wt), C);
        if (!isNonnegativeIntVector(deltaFromHighest)) {
          weightMultMemo.set(mk, 0);
          return 0;
        }
        const top = add(highest, rho);
        const target = add(wt, rho);
        let total = 0;
        for (const ow of orbit(top)) total += ow.sign * partitionFunction(sub(ow.wt, target));
        weightMultMemo.set(mk, total);
        return total;
      }
      function support(highest) {
        const orbitHighest = orbit(highest);
        const maxDelta = Array(C.length).fill(0);
        for (const ow of orbitHighest) {
          const d = dynkinToSimple(sub(highest, ow.wt), C);
          if (d) for (let i=0;i<d.length;i++) maxDelta[i] = Math.max(maxDelta[i], d[i]);
        }
        const box = maxDelta.reduce((p,x) => p * (x + 1), 1);
        if (box > MAX_SUPPORT_BOX) throw new Error(`Weight support search box has ${box} points. Try smaller diagrams/rank, or use stable mode.`);
        const out = new Map();
        function rec(i, delta) {
          if (i === maxDelta.length) {
            const wt = sub(highest, simpleToDynkin(delta, C));
            const m = weightMultiplicity(highest, wt);
            if (m > 0) out.set(key(wt), { wt, mult: m });
            return;
          }
          for (let x=0; x<=maxDelta[i]; x++) { delta[i] = x; rec(i + 1, delta); }
        }
        rec(0, Array(C.length).fill(0));
        return Array.from(out.values());
      }
      function tensorCoeff(lambda, mu, nu) {
        let total = 0;
        const nuRho = add(nu, rho);
        const lambdaRho = add(lambda, rho);
        for (const ow of orbit(nuRho)) total += ow.sign * weightMultiplicity(mu, sub(ow.wt, lambdaRho));
        return Math.max(0, Math.round(total));
      }
      return { C, rootsSimple, rho, orbit, support, tensorCoeff, weightMultiplicity };
    }

    function weightMultiplicityByWeylCharacter(highestLabels, weightLabels, type, rank) {
      if (!isDominantDynkin(highestLabels)) throw new Error('Weight multiplicity requires a dominant integral highest weight.');
      const C = cartanMatrix(type, rank);
      const delta = dynkinToSimple(sub(highestLabels, weightLabels), C);
      if (!isNonnegativeIntVector(delta)) {
        return { value: 0, engine: 'character multiplicity', checked: 'root-lattice rejection' };
      }
      const ctx = makeWeylContext(type, rank);
      const value = ctx.weightMultiplicity(highestLabels, weightLabels);
      return { value, engine: 'character multiplicity', checked: 'character expansion' };
    }

    function decomposeFixedRankTypeA(lambdaRows, muRows, rank) {
      // Exact finite-rank A_n tensor product.  Regard the page diagram
      // (a_1,...,a_n) as the GL_{n+1} partition (a_1,...,a_n,0), decompose
      // by Littlewood--Richardson coefficients, then quotient by determinant
      // twists by removing the last row from every output partition.
      const glRank = rank + 1;
      const lambda = trimPartition(lambdaRows).slice(0, glRank);
      const mu = trimPartition(muRows).slice(0, glRank);
      const total = sizeOf(lambda) + sizeOf(mu);
      if (total > MAX_EXACT_CELLS) throw new Error(`Fixed-rank type A exact LR computation capped at ${MAX_EXACT_CELLS} total boxes.`);
      const combined = new Map();
      for (const nuGL of partitionsOf(total, total, glRank)) {
        if (!containsPartition(nuGL, lambda)) continue;
        const c = lrCoefficient(lambda, mu, nuGL);
        if (!c) continue;
        const detTwist = nuGL[glRank - 1] || 0;
        const diagramRows = Array.from({length: rank}, (_, i) => (nuGL[i] || 0) - detTwist);
        const labels = diagramToDynkinLabels(diagramRows, rank);
        const k = key(labels);
        const old = combined.get(k);
        if (old) old.coefficient += c;
        else combined.set(k, { labels, nu: dynkinLabelsToDiagram(labels), coefficient: c, dimension: null });
      }
      const C = cartanMatrix('A', rank);
      for (const term of combined.values()) term.dimension = weylDimension(term.labels, C);
      return Array.from(combined.values()).filter(t => t.coefficient > 0).sort(compareTerms);
    }

    function shiftedWeylStraighten(labels, C) {
      // Move labels + rho into the dominant chamber by the shifted Weyl action.
      // Returns { labels, sign, singular }.  It is deliberately cheap: no
      // character expansion and no full Weyl orbit enumeration.
      const rho = Array(C.length).fill(1);
      let x = add(labels, rho);
      let sign = 1;
      const seen = new Set();
      for (let steps = 0; steps < 4 * C.length * C.length + 20; steps++) {
        if (x.some(v => v === 0)) return { singular: true, labels: null, sign: 0 };
        const i = x.findIndex(v => v < 0);
        if (i < 0) {
          const dominant = sub(x, rho);
          if (dominant.some(v => v < 0)) return { singular: true, labels: null, sign: 0 };
          return { singular: false, labels: dominant, sign };
        }
        const k = key(x);
        if (seen.has(k)) return { singular: true, labels: null, sign: 0 };
        seen.add(k);
        x = reflectDynkin(x, i, C);
        sign *= -1;
      }
      return { singular: true, labels: null, sign: 0 };
    }

    function cartanSymmetrizer(C) {
      // Return positive numbers d_i with d_j C_{ij} = d_i C_{ji}.
      // Then (α_i, α_j) = d_j C_{ij} gives a symmetric bilinear form
      // in the simple-root basis, up to a harmless common scalar.
      const n = C.length;
      const d = Array(n).fill(null);
      d[0] = 1;
      const q = [0];
      for (let head = 0; head < q.length; head++) {
        const i = q[head];
        for (let j = 0; j < n; j++) {
          if (i === j || !C[i][j] || !C[j][i]) continue;
          const val = d[i] * C[j][i] / C[i][j];
          if (d[j] == null) { d[j] = val; q.push(j); }
        }
      }
      return d.map(x => x == null ? 1 : x);
    }

    function makeDynkinInnerProduct(C) {
      const d = cartanSymmetrizer(C);
      const B = C.map((row, i) => row.map((_, j) => C[i][j] * d[j]));
      return function innerDynkin(a, b) {
        const as = solveLinear(transpose(C), a);
        const bs = solveLinear(transpose(C), b);
        if (!as || !bs) return NaN;
        let total = 0;
        for (let i = 0; i < C.length; i++) {
          for (let j = 0; j < C.length; j++) total += as[i] * B[i][j] * bs[j];
        }
        return total;
      };
    }

    function makeDynkinGram(C) {
      // Gram matrix in Dynkin-label / fundamental-weight coordinates.
      // The form is induced from the standard W-invariant form on X^*(T).
      const inner = makeDynkinInnerProduct(C);
      const n = C.length;
      const G = Array.from({length:n}, () => Array(n).fill(0));
      for (let i = 0; i < n; i++) {
        const ei = Array(n).fill(0); ei[i] = 1;
        for (let j = 0; j < n; j++) {
          const ej = Array(n).fill(0); ej[j] = 1;
          G[i][j] = inner(ei, ej);
        }
      }
      return G;
    }

    function normSquaredDynkin(labels, G) {
      let total = 0;
      for (let i = 0; i < labels.length; i++) {
        if (!labels[i]) continue;
        for (let j = 0; j < labels.length; j++) {
          if (labels[j]) total += labels[i] * labels[j] * G[i][j];
        }
      }
      return total;
    }

    function dominantNormBoundCandidates(lambdaRows, muRows, type, rank, C) {
      // Candidate source suggested by the user:
      // enumerate dominant nonnegative highest weights γ with
      //     ||γ|| <= ||λ|| + ||μ||
      // for the standard invariant inner product on X^*(T).
      // This avoids Weyl-group candidate loops and also avoids Young-diagram
      // containment heuristics, which are unreliable for exceptional types.
      const lambdaLabels = diagramToDynkinLabels(lambdaRows, rank);
      const muLabels = diagramToDynkinLabels(muRows, rank);
      const G = makeDynkinGram(C);
      const lambdaLen = Math.sqrt(Math.max(0, normSquaredDynkin(lambdaLabels, G)));
      const muLen = Math.sqrt(Math.max(0, normSquaredDynkin(muLabels, G)));
      const radius = lambdaLen + muLen;
      const radius2 = radius * radius + 1e-8;
      const n = C.length;

      // Since fundamental weights have nonnegative pairwise inner products in
      // finite type, each coordinate is bounded by the one-coordinate norm.
      const maxCoord = [];
      let searchBox = 1;
      for (let i = 0; i < n; i++) {
        const ei = Array(n).fill(0); ei[i] = 1;
        const unit2 = normSquaredDynkin(ei, G);
        const m = unit2 > 1e-12 ? Math.floor(radius / Math.sqrt(unit2) + 1e-9) : 0;
        maxCoord.push(Math.max(0, m));
        searchBox *= (Math.max(0, m) + 1);
        if (searchBox > MAX_NORM_BOUND_CANDIDATES * 200) {
          throw new Error(`Norm-bound candidate box has ${searchBox} points before pruning. Try smaller diagrams/rank.`);
        }
      }

      const candidates = new Map();
      function rec(i, acc) {
        const partialNorm2 = normSquaredDynkin(acc, G);
        if (partialNorm2 > radius2) return;
        if (i === n) {
          const k = key(acc);
          candidates.set(k, {
            labels: acc.slice(),
            nu: dynkinLabelsToDiagram(acc),
            candidateSource: `norm ≤ ${radius.toFixed(4)}`,
            normSquared: partialNorm2
          });
          if (candidates.size > MAX_NORM_BOUND_CANDIDATES) {
            throw new Error(`Norm-bound candidate list exceeded ${MAX_NORM_BOUND_CANDIDATES}; try smaller diagrams/rank.`);
          }
          return;
        }
        for (let x = 0; x <= maxCoord[i]; x++) {
          acc[i] = x;
          rec(i + 1, acc);
        }
        acc[i] = 0;
      }
      rec(0, Array(n).fill(0));
      const arr = Array.from(candidates.values()).sort((a,b) => compareTerms({nu:a.nu, labels:a.labels}, {nu:b.nu, labels:b.labels}));
      arr.radius = radius;
      arr.searchBox = searchBox;
      arr.coordinateBounds = maxCoord;
      return arr;
    }

    function irreducibleCharacterFreudenthal(highest, C, cap = MAX_FREUDENTHAL_WEIGHTS) {
      if (!isDominantDynkin(highest)) throw new Error('Freudenthal character generation requires a dominant integral highest weight.');
      // Build the full weight-multiplicity dictionary of V^highest using
      // Freudenthal recursion.  This replaces the old Kostant partition
      // recursion in tensor-product calculations.
      const n = C.length;
      const rho = Array(n).fill(1);
      const rootsSimple = positiveRoots(C);
      const rootsDynkin = rootsSimple.map(r => simpleToDynkin(r, C));
      const simpleRootsDynkin = Array.from({length:n}, (_, i) => {
        const e = Array(n).fill(0); e[i] = 1;
        return simpleToDynkin(e, C);
      });
      const inner = makeDynkinInnerProduct(C);
      const topNorm = inner(add(highest, rho), add(highest, rho));
      const char = new Map();
      const tested = new Set();
      const topKey = key(highest);
      char.set(topKey, { wt: highest.slice(), mult: 1, level: 0 });
      tested.add(topKey);
      let frontier = [highest.slice()];
      let level = 0;

      function multiplicityByFreudenthal(wt) {
        const wtRho = add(wt, rho);
        const denom = topNorm - inner(wtRho, wtRho);
        if (!(denom > 1e-10)) return 0;
        let sum = 0;
        for (const alpha of rootsDynkin) {
          let z = add(wt, alpha);
          while (true) {
            const item = char.get(key(z));
            if (!item) break;
            sum += inner(z, alpha) * item.mult;
            z = add(z, alpha);
          }
        }
        const value = (2 * sum) / denom;
        if (!Number.isFinite(value)) return 0;
        const rounded = Math.round(value);
        return Math.abs(value - rounded) < 1e-6 ? Math.max(0, rounded) : Math.max(0, rounded);
      }

      while (frontier.length) {
        const candidates = new Map();
        for (const wt of frontier) {
          for (const alpha of simpleRootsDynkin) {
            const cand = sub(wt, alpha);
            const k = key(cand);
            if (tested.has(k) || candidates.has(k)) continue;
            // It must still be below the highest weight in the positive root lattice.
            const delta = dynkinToSimple(sub(highest, cand), C);
            if (!isNonnegativeIntVector(delta)) continue;
            candidates.set(k, cand);
          }
        }
        if (!candidates.size) break;
        const next = [];
        level += 1;
        for (const [k, cand] of candidates) {
          tested.add(k);
          const mult = multiplicityByFreudenthal(cand);
          if (mult > 0) {
            char.set(k, { wt: cand, mult, level });
            next.push(cand);
            if (char.size > cap) throw new Error(`Freudenthal character generation exceeded ${cap} weights. Try smaller diagrams/rank.`);
          }
        }
        frontier = next;
      }
      char.highest = highest.slice();
      return char;
    }

    function kostkaNumber(lambdaRows, contentRows) {
      const shape = trimPartition(lambdaRows), content = trimPartition(contentRows);
      const total = sizeOf(shape);
      if (total !== sizeOf(content)) return 0;
      if (total === 0) return 1;
      if (total > MAX_EXACT_CELLS) throw new Error(`Kostka calculation is capped at ${MAX_EXACT_CELLS} boxes in this browser page.`);
      const m = content.length;
      if (m === 0) return 0;
      const cells = [];
      for (let r=0;r<shape.length;r++) for (let c=0;c<shape[r];c++) cells.push([r,c]);
      const grid = shape.map(len => Array(len).fill(0));
      const supply = content.slice();
      let count = 0, steps = 0;
      function rec(i) {
        if (++steps > MAX_KOSTKA_STEPS) throw new Error(`Kostka recursion exceeded ${MAX_KOSTKA_STEPS} steps; try a smaller shape/content.`);
        if (i === cells.length) { count += 1; return; }
        const [r,c] = cells[i];
        let lo = 1;
        if (c > 0) lo = Math.max(lo, grid[r][c-1]);
        if (r > 0 && c < shape[r-1]) lo = Math.max(lo, grid[r-1][c] + 1);
        for (let v=lo; v<=m; v++) {
          if (supply[v-1] <= 0) continue;
          grid[r][c] = v; supply[v-1] -= 1;
          rec(i + 1);
          supply[v-1] += 1; grid[r][c] = 0;
        }
      }
      rec(0);
      return count;
    }

    function semistandardTableaux(lambdaRows, contentRows) {
      const shape = trimPartition(lambdaRows), content = trimPartition(contentRows);
      const total = sizeOf(shape);
      if (total !== sizeOf(content)) return { tableaux: [], count: 0, capped: false, steps: 0, message: '|λ| and |μ| are different.' };
      if (total === 0) return { tableaux: [[]], count: 1, capped: false, steps: 0, message: '' };
      if (total > MAX_EXACT_CELLS) throw new Error(`Tableaux enumeration is capped at ${MAX_EXACT_CELLS} boxes in this browser page.`);
      const m = content.length;
      if (m === 0) return { tableaux: [], count: 0, capped: false, steps: 0, message: 'Nonempty shape with empty content.' };
      const cells = [];
      for (let r = 0; r < shape.length; r++) for (let c = 0; c < shape[r]; c++) cells.push([r, c]);
      const grid = shape.map(len => Array(len).fill(0));
      const supply = content.slice();
      const tableaux = [];
      let steps = 0, capped = false;
      function rec(i) {
        if (++steps > MAX_KOSTKA_STEPS) throw new Error(`Tableaux recursion exceeded ${MAX_KOSTKA_STEPS} steps; try a smaller shape/content.`);
        if (i === cells.length) {
          tableaux.push(grid.map(row => row.slice()));
          if (tableaux.length >= MAX_KOSTKA_TABLEAUX) capped = true;
          return;
        }
        if (capped) return;
        const [r, c] = cells[i];
        let lo = 1;
        if (c > 0) lo = Math.max(lo, grid[r][c - 1]);
        if (r > 0 && c < shape[r - 1]) lo = Math.max(lo, grid[r - 1][c] + 1);
        for (let v = lo; v <= m; v++) {
          if (supply[v - 1] <= 0) continue;
          grid[r][c] = v;
          supply[v - 1] -= 1;
          rec(i + 1);
          supply[v - 1] += 1;
          grid[r][c] = 0;
          if (capped) return;
        }
      }
      rec(0);
      return { tableaux, count: tableaux.length, capped, steps, message: capped ? `Display capped at ${MAX_KOSTKA_TABLEAUX} tableaux.` : '' };
    }

    function factorialNumber(n) {
      let r = 1;
      for (let i = 2; i <= n; i++) r *= i;
      return r;
    }

    function standardTableauxCount(lambda) {
      lambda = trimPartition(lambda);
      const n = sizeOf(lambda);
      if (n === 0) return 1;
      const cols = conjugatePartition(lambda);
      let denom = 1;
      for (let r = 0; r < lambda.length; r++) {
        for (let c = 0; c < lambda[r]; c++) {
          denom *= (lambda[r] - c) + ((cols[c] || 0) - r - 1);
        }
      }
      return Math.round(factorialNumber(n) / denom);
    }

    function zValue(cycleType) {
      const counts = new Map();
      for (const p of trimPartition(cycleType)) counts.set(p, (counts.get(p) || 0) + 1);
      let z = 1;
      for (const [part, mult] of counts.entries()) z *= Math.pow(part, mult) * factorialNumber(mult);
      return z;
    }

    function subpartitionsOfShape(shape, targetSize) {
      shape = trimPartition(shape);
      const out = [];
      function rec(i, prev, acc, used) {
        if (used > targetSize) return;
        if (i === shape.length) {
          if (used === targetSize) out.push(trimPartition(acc));
          return;
        }
        const max = Math.min(shape[i], prev, targetSize - used);
        for (let x = max; x >= 0; x--) {
          acc.push(x);
          rec(i + 1, x, acc, used + x);
          acc.pop();
        }
      }
      rec(0, shape[0] || 0, [], 0);
      const seen = new Set();
      return out.filter((p) => {
        const k = partitionKey(p);
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
      });
    }

    function skewCellList(outer, inner) {
      outer = trimPartition(outer); inner = trimPartition(inner);
      const cells = [];
      for (let r = 0; r < outer.length; r++) {
        for (let c = inner[r] || 0; c < outer[r]; c++) cells.push([r, c]);
      }
      return cells;
    }

    function isConnectedCellSet(cells) {
      if (!cells.length) return false;
      const set = new Set(cells.map(([r, c]) => r + ',' + c));
      const stack = [cells[0].join(',')];
      const seen = new Set(stack);
      while (stack.length) {
        const [r, c] = stack.pop().split(',').map(Number);
        for (const [rr, cc] of [[r + 1, c], [r - 1, c], [r, c + 1], [r, c - 1]]) {
          const k = rr + ',' + cc;
          if (set.has(k) && !seen.has(k)) { seen.add(k); stack.push(k); }
        }
      }
      return seen.size === cells.length;
    }

    function hasTwoByTwo(cells) {
      const set = new Set(cells.map(([r, c]) => r + ',' + c));
      for (const [r, c] of cells) {
        if (set.has(r + ',' + c) && set.has((r + 1) + ',' + c) && set.has(r + ',' + (c + 1)) && set.has((r + 1) + ',' + (c + 1))) return true;
      }
      return false;
    }

    function isBorderStrip(outer, inner) {
      const cells = skewCellList(outer, inner);
      return cells.length > 0 && isConnectedCellSet(cells) && !hasTwoByTwo(cells);
    }

    function rimHookRemovals(shape, stripSize) {
      shape = trimPartition(shape);
      const targetSize = sizeOf(shape) - stripSize;
      if (targetSize < 0) return [];
      const out = [];
      for (const inner of subpartitionsOfShape(shape, targetSize)) {
        if (!isBorderStrip(shape, inner)) continue;
        const cells = skewCellList(shape, inner);
        const rows = new Set(cells.map(([r]) => r));
        out.push({ remaining: inner, height: rows.size - 1 });
      }
      return out;
    }

    function symmetricCharacter(shape, cycleType) {
      shape = trimPartition(shape);
      cycleType = trimPartition(cycleType).sort((a, b) => b - a);
      if (sizeOf(shape) !== sizeOf(cycleType)) return 0;
      const memoKey = partitionKey(shape) + '|' + partitionKey(cycleType);
      if (symmetricCharacterMemo.has(memoKey)) return symmetricCharacterMemo.get(memoKey);
      let val;
      if (!cycleType.length) {
        val = shape.length ? 0 : 1;
      } else {
        const k = cycleType[0];
        const rest = cycleType.slice(1);
        val = 0;
        for (const rem of rimHookRemovals(shape, k)) {
          val += (rem.height % 2 ? -1 : 1) * symmetricCharacter(rem.remaining, rest);
        }
      }
      symmetricCharacterMemo.set(memoKey, val);
      return val;
    }

    function kroneckerCoefficient(lambda, mu, nu) {
      const n = sizeOf(lambda);
      if (sizeOf(mu) !== n || sizeOf(nu) !== n) return 0;
      let total = 0;
      for (const rho of partitionsOf(n)) {
        total += symmetricCharacter(lambda, rho) * symmetricCharacter(mu, rho) * symmetricCharacter(nu, rho) / zValue(rho);
      }
      return Math.max(0, Math.round(total));
    }

    function decomposeKronecker(lambda, mu) {
      lambda = trimPartition(lambda); mu = trimPartition(mu);
      const n = sizeOf(lambda);
      if (n !== sizeOf(mu)) throw new Error('Kronecker decomposition requires |λ| = |μ|.');
      if (n > MAX_KRONECKER_BOXES) throw new Error(`Kronecker computation capped at ${MAX_KRONECKER_BOXES} boxes.`);
      const terms = [];
      for (const nu of partitionsOf(n)) {
        const c = kroneckerCoefficient(lambda, mu, nu);
        if (c) terms.push({ nu, coefficient: c, dimension: standardTableauxCount(nu) });
      }
      const found = terms.reduce((s, t) => s + t.coefficient * t.dimension, 0);
      const target = standardTableauxCount(lambda) * standardTableauxCount(mu);
      terms.dimensionCheck = { found, target, ok: found === target };
      return terms.sort(compareTerms);
    }

    function addToPowerMap(map, partition, coeff) {
      if (Math.abs(coeff) < 1e-12) return;
      const p = trimPartition(partition).sort((a, b) => b - a);
      const k = partitionKey(p);
      map.set(k, (map.get(k) || 0) + coeff);
      if (map.size > MAX_POWER_SUM_TERMS) throw new Error(`Power-sum expansion exceeded ${MAX_POWER_SUM_TERMS} terms.`);
    }

    function multiplyPowerMaps(A, B) {
      const out = new Map();
      for (const [ka, ca] of A.entries()) {
        const pa = ka ? ka.split(',').map(Number) : [];
        for (const [kb, cb] of B.entries()) {
          const pb = kb ? kb.split(',').map(Number) : [];
          addToPowerMap(out, pa.concat(pb), ca * cb);
        }
      }
      return out;
    }

    function scaledSchurPowerExpansion(shape, scalePart) {
      shape = trimPartition(shape);
      const n = sizeOf(shape);
      const out = new Map();
      for (const beta of partitionsOf(n)) {
        const coeff = symmetricCharacter(shape, beta) / zValue(beta);
        if (!coeff) continue;
        addToPowerMap(out, beta.map((x) => x * scalePart), coeff);
      }
      return out;
    }

    function plethysmPowerExpansion(lambda, mu) {
      const m = sizeOf(lambda), n = sizeOf(mu);
      if (m === 0) return new Map([['', 1]]);
      if (n === 0) throw new Error('Plethysm with empty μ is not implemented in this browser card.');
      if (m * n > MAX_PLETHYSM_BOXES) throw new Error(`Plethysm computation capped at ${MAX_PLETHYSM_BOXES} output boxes.`);
      const total = new Map();
      for (const alpha of partitionsOf(m)) {
        const outer = symmetricCharacter(lambda, alpha) / zValue(alpha);
        if (!outer) continue;
        let product = new Map([['', 1]]);
        for (const part of alpha) product = multiplyPowerMaps(product, scaledSchurPowerExpansion(mu, part));
        for (const [rhoKey, coeff] of product.entries()) {
          const rho = rhoKey ? rhoKey.split(',').map(Number) : [];
          addToPowerMap(total, rho, outer * coeff);
        }
      }
      return total;
    }

    function decomposePlethysm(lambda, mu) {
      lambda = trimPartition(lambda); mu = trimPartition(mu);
      const totalSize = sizeOf(lambda) * sizeOf(mu);
      if (totalSize > MAX_PLETHYSM_BOXES) throw new Error(`Plethysm computation capped at ${MAX_PLETHYSM_BOXES} output boxes.`);
      const power = plethysmPowerExpansion(lambda, mu);
      const terms = [];
      for (const nu of partitionsOf(totalSize)) {
        let coeff = 0;
        for (const [rhoKey, a] of power.entries()) {
          const rho = rhoKey ? rhoKey.split(',').map(Number) : [];
          coeff += a * symmetricCharacter(nu, rho);
        }
        const c = Math.round(coeff);
        if (c) terms.push({ nu, coefficient: c });
      }
      terms.powerTermCount = power.size;
      terms.dimensionCheck = null;
      return terms.sort(compareTerms);
    }

    function addToWeightCharacter(map, wt, coeff, cap = MAX_SCHUR_FUNCTOR_CHAR_TERMS) {
      if (Math.abs(coeff) < 1e-10) return;
      const k = key(wt);
      const next = (map.get(k) || 0) + coeff;
      if (Math.abs(next) < 1e-10) map.delete(k);
      else map.set(k, next);
      if (map.size > cap) throw new Error(`Schur-functor character expansion exceeded ${cap} weights; try a smaller λ or μ.`);
    }

    function freudenthalMapToWeightCharacter(char) {
      const out = new Map();
      for (const item of char.values()) addToWeightCharacter(out, item.wt, item.mult);
      return out;
    }

    function multiplyWeightCharacters(A, B, cap = MAX_SCHUR_FUNCTOR_CHAR_TERMS) {
      const out = new Map();
      for (const [ka, ca] of A.entries()) {
        const a = ka ? ka.split(',').map(Number) : [];
        for (const [kb, cb] of B.entries()) {
          const b = kb ? kb.split(',').map(Number) : [];
          const wt = a.map((x, i) => x + (b[i] || 0));
          addToWeightCharacter(out, wt, ca * cb, cap);
        }
      }
      return out;
    }

    function scaleWeightCharacterWeights(A, factor, cap = MAX_SCHUR_FUNCTOR_CHAR_TERMS) {
      const out = new Map();
      for (const [ka, ca] of A.entries()) {
        const a = ka ? ka.split(',').map(Number) : [];
        addToWeightCharacter(out, a.map(x => x * factor), ca, cap);
      }
      return out;
    }

    function schurFunctorCharacter(muRows, baseChar, rank) {
      // Character formula for Schur functors:
      //   ch(S^μ W) = Σ_{α⊢|μ|} χ^μ(α)/z_α · ∏_{k∈α} ψ_k(ch W),
      // where ψ_k(e^ν)=e^{kν}.  Here ch W is the finite-type character of V^λ.
      const mu = trimPartition(muRows);
      const degree = sizeOf(mu);
      const zero = Array(rank).fill(0);
      if (degree === 0) return { char: new Map([[key(zero), 1]]), powerTermCount: 1 };
      if (degree > MAX_PLETHYSM_BOXES) throw new Error(`Schur functor degree capped at ${MAX_PLETHYSM_BOXES}.`);
      const total = new Map();
      let powerTermCount = 0;
      for (const alpha of partitionsOf(degree)) {
        const outer = symmetricCharacter(mu, alpha) / zValue(alpha);
        if (!outer) continue;
        let product = new Map([[key(zero), 1]]);
        for (const part of alpha) {
          const adams = scaleWeightCharacterWeights(baseChar, part);
          product = multiplyWeightCharacters(product, adams);
        }
        powerTermCount += product.size;
        for (const [wtKey, coeff] of product.entries()) {
          const wt = wtKey ? wtKey.split(',').map(Number) : zero.slice();
          addToWeightCharacter(total, wt, outer * coeff);
        }
      }
      // Clean numerical roundoff: final multiplicities are integers.
      for (const [k, v] of Array.from(total.entries())) {
        const r = Math.round(v);
        if (Math.abs(v - r) < 1e-7) {
          if (r === 0) total.delete(k);
          else total.set(k, r);
        }
      }
      return { char: total, powerTermCount };
    }

    function chooseHighestResidualWeight(residual, C) {
      const G = makeDynkinGram(C);
      const candidates = [];
      for (const [k, coeff] of residual.entries()) {
        const c = Math.round(coeff);
        if (c <= 0 || Math.abs(coeff - c) > 1e-6) continue;
        const wt = k ? k.split(',').map(Number) : [];
        if (!wt.every(x => x >= 0)) continue;
        candidates.push({ wt, coeff: c, norm: normSquaredDynkin(wt, G), height: wt.reduce((a,b)=>a+b,0) });
      }
      if (!candidates.length) return null;
      candidates.sort((a, b) => {
        const dn = b.norm - a.norm;
        if (Math.abs(dn) > 1e-8) return dn;
        const dh = b.height - a.height;
        if (dh) return dh;
        for (let i = 0; i < Math.max(a.wt.length, b.wt.length); i++) {
          const d = (b.wt[i] || 0) - (a.wt[i] || 0);
          if (d) return d;
        }
        return 0;
      });
      return candidates[0];
    }

    function cleanResidualCharacter(residual) {
      for (const [k, v] of Array.from(residual.entries())) {
        const r = Math.round(v);
        if (Math.abs(v - r) < 1e-7) {
          if (r === 0) residual.delete(k);
          else residual.set(k, r);
        } else if (Math.abs(v) < 1e-8) residual.delete(k);
      }
    }

    function decomposeCharacterByHighestWeightPeeling(characterMap, type, rank, C) {
      // Decompose a finite-type character into irreducibles by repeatedly taking
      // the largest dominant residual weight and subtracting that irreducible
      // character.  This produces terms V^γ, so the final answer respects the
      // selected Dynkin type/rank rather than ordinary symmetric-function
      // plethysm alone.
      const residual = new Map(characterMap);
      cleanResidualCharacter(residual);
      const terms = [];
      let iterations = 0;
      while (residual.size) {
        if (++iterations > MAX_SCHUR_FUNCTOR_DECOMP_TERMS) throw new Error(`Schur-functor decomposition exceeded ${MAX_SCHUR_FUNCTOR_DECOMP_TERMS} irreducible terms.`);
        const top = chooseHighestResidualWeight(residual, C);
        if (!top) break;
        const mult = top.coeff;
        const gammaChar = irreducibleCharacterFreudenthal(top.wt, C);
        for (const item of gammaChar.values()) {
          const k = key(item.wt);
          residual.set(k, (residual.get(k) || 0) - mult * item.mult);
        }
        cleanResidualCharacter(residual);
        terms.push({
          labels: top.wt,
          nu: dynkinLabelsToDiagram(top.wt),
          coefficient: mult,
          dimensionBigInt: weylDimensionBigInt(top.wt, C),
          dimension: weylDimension(top.wt, C),
          characterWeights: gammaChar.size
        });
      }
      terms.residualWeightCount = residual.size;
      terms.residualL1 = Array.from(residual.values()).reduce((s, x) => s + Math.abs(x), 0);
      return terms.sort(compareTerms);
    }

    function decomposeSchurFunctorFiniteType(lambdaRows, muRows, type, rank) {
      const C = cartanMatrix(type, rank);
      const lambdaLabels = diagramToDynkinLabels(lambdaRows, rank);
      const baseCharFreudenthal = irreducibleCharacterFreudenthal(lambdaLabels, C);
      const baseChar = freudenthalMapToWeightCharacter(baseCharFreudenthal);
      const schurCharData = schurFunctorCharacter(muRows, baseChar, rank);
      const terms = decomposeCharacterByHighestWeightPeeling(schurCharData.char, type, rank, C);
      const targetDimension = Math.round(Array.from(schurCharData.char.values()).reduce((s, x) => s + x, 0));
      let found = 0n;
      for (const t of terms) found += BigInt(t.coefficient) * t.dimensionBigInt;
      terms.dimensionCheck = { found: found.toString(), target: String(targetDimension), ok: found === BigInt(targetDimension) };
      terms.baseCharacterWeightCount = baseCharFreudenthal.size;
      terms.schurCharacterWeightCount = schurCharData.char.size;
      terms.powerTermCount = schurCharData.powerTermCount;
      terms.lambdaLabels = lambdaLabels;
      return terms;
    }

    function decomposeByCandidatesBrauerKlimyk(lambdaRows, muRows, candidates, type, rank, C) {
      // Brauer--Klimyk / Klimyk--Racah--Speiser engine:
      // compute the character of the smaller factor by Freudenthal recursion,
      // then straighten larger + η under the shifted Weyl action.  The supplied
      // candidate list is used only as a filter for allowed highest weights.
      const lambdaLabels = diagramToDynkinLabels(lambdaRows, rank);
      const muLabels = diagramToDynkinLabels(muRows, rank);
      const dimLambda = weylDimensionBigInt(lambdaLabels, C);
      const dimMu = weylDimensionBigInt(muLabels, C);
      const useMuAsCharacter = dimMu <= dimLambda;
      const charHighest = useMuAsCharacter ? muLabels : lambdaLabels;
      const larger = useMuAsCharacter ? lambdaLabels : muLabels;
      const char = irreducibleCharacterFreudenthal(charHighest, C);
      const wanted = new Map(candidates.map(c => [key(c.labels), c]));
      const combined = new Map();
      for (const item of char.values()) {
        const straight = shiftedWeylStraighten(add(larger, item.wt), C);
        if (straight.singular) continue;
        const k = key(straight.labels);
        const cand = wanted.get(k);
        if (!cand) continue;
        const coeff = straight.sign * item.mult;
        if (!coeff) continue;
        const old = combined.get(k);
        if (old) old.coefficient += coeff;
        else combined.set(k, {
          labels: straight.labels,
          nu: dynkinLabelsToDiagram(straight.labels),
          coefficient: coeff,
          dimensionBigInt: weylDimensionBigInt(straight.labels, C),
          candidateSource: cand.sourceNu ? `subdiagram/source ${partitionToString(cand.sourceNu)}` : 'candidate',
          sourceNu: cand.sourceNu,
          stableCoefficient: cand.stableCoefficient,
          characterWeights: char.size,
          characterSide: useMuAsCharacter ? 'μ' : 'λ'
        });
      }
      const terms = Array.from(combined.values()).filter(t => t.coefficient > 0).sort(compareTerms);
      terms.characterWeightCount = char.size;
      terms.characterSide = useMuAsCharacter ? 'μ' : 'λ';
      return terms;
    }

    function dimensionCheckForTerms(lambdaRows, muRows, terms, type, rank, C) {
      const lambdaLabels = diagramToDynkinLabels(lambdaRows, rank);
      const muLabels = diagramToDynkinLabels(muRows, rank);
      const target = weylDimensionBigInt(lambdaLabels, C) * weylDimensionBigInt(muLabels, C);
      let found = 0n;
      for (const t of terms) {
        const dim = t.dimensionBigInt != null ? t.dimensionBigInt : weylDimensionBigInt(t.labels, C);
        t.dimensionBigInt = dim;
        t.dimension = dim.toString();
        found += BigInt(t.coefficient) * dim;
      }
      const missing = target - found;
      return { target: target.toString(), found: found.toString(), missing: missing.toString(), ok: missing === 0n };
    }

    function appendWarning(existing, extra) {
      return existing ? existing + ' ' + extra : extra;
    }

    function decomposeFixedRank(lambdaRows, muRows, type, rank) {
      if (type === 'A') {
        const terms = decomposeFixedRankTypeA(lambdaRows, muRows, rank);
        const C = cartanMatrix(type, rank);
        for (const term of terms) term.dimensionBigInt = weylDimensionBigInt(term.labels, C);
        terms.dimensionCheck = dimensionCheckForTerms(lambdaRows, muRows, terms, type, rank, C);
        if (!terms.dimensionCheck.ok) {
          terms.warning = appendWarning(terms.warning, `Dimension check failed: displayed dimension ${terms.dimensionCheck.found} but tensor product dimension is ${terms.dimensionCheck.target}; missing ${terms.dimensionCheck.missing}.`);
        }
        return terms;
      }

      const C = cartanMatrix(type, rank);
      if (!['B','C','D'].includes(type) && !isExceptionalType(type)) {
        throw new Error('Unsupported fixed-rank type.');
      }

      const candidates = dominantNormBoundCandidates(lambdaRows, muRows, type, rank, C);
      const candidateCount = candidates.length;
      const candidateSource = `dominant norm-bound weights (‖γ‖ ≤ ‖λ‖ + ‖μ‖, radius ${candidates.radius.toFixed(4)})`;

      const terms = decomposeByCandidatesBrauerKlimyk(lambdaRows, muRows, candidates, type, rank, C);
      terms.candidateCount = candidateCount;
      terms.candidateSource = candidateSource;
      terms.candidateRadius = candidates.radius;
      terms.candidateCoordinateBounds = candidates.coordinateBounds;
      terms.candidateSearchBox = candidates.searchBox;
      terms.dimensionCheck = dimensionCheckForTerms(lambdaRows, muRows, terms, type, rank, C);
      terms.engineInfo = `Candidate source: dominant norm ball with coordinate bounds [${candidates.coordinateBounds.join(', ')}] (${candidateCount} candidates after pruning). Coefficient engine: Freudenthal character generation for ${terms.characterSide || 'the smaller factor'} (${terms.characterWeightCount || 0} weights) plus Brauer–Klimyk straightening; no Kostant partition recursion is used.`;
      if (!terms.dimensionCheck.ok) {
        const diffText = terms.dimensionCheck.missing.startsWith('-')
          ? `overcount ${terms.dimensionCheck.missing.slice(1)}`
          : `missing ${terms.dimensionCheck.missing}`;
        terms.warning = appendWarning(terms.warning, `Dimension check failed: displayed dimension ${terms.dimensionCheck.found} but tensor product dimension is ${terms.dimensionCheck.target}; ${diffText}.`);
      }
      return terms;
    }

    function compareTerms(a,b) {
      const A = trimPartition(a.nu), B = trimPartition(b.nu);
      const s = sizeOf(B) - sizeOf(A); if (s) return s;
      for (let i=0;i<Math.max(A.length,B.length);i++) { const d = (B[i]||0) - (A[i]||0); if (d) return d; }
      const la = a.labels || [], lb = b.labels || [];
      for (let i=0;i<Math.max(la.length,lb.length);i++) { const d=(lb[i]||0)-(la[i]||0); if(d) return d; }
      return 0;
    }

    function fitsGrassmannianRectangle(partition, r, k) {
      const p = trimPartition(partition);
      return p.length <= r && p.every(x => x <= k);
    }

    function decomposeGrassmannianCup(lambdaRows, muRows, r, k) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      if (!fitsGrassmannianRectangle(lambda, r, k)) throw new Error(`λ must fit inside the ${r} × ${k} Grassmannian rectangle.`);
      if (!fitsGrassmannianRectangle(mu, r, k)) throw new Error(`μ must fit inside the ${r} × ${k} Grassmannian rectangle.`);
      const total = sizeOf(lambda) + sizeOf(mu);
      if (total > r * k) {
        const empty = [];
        empty.rectangle = { r, k, n: r + k };
        return empty;
      }
      if (total > MAX_EXACT_CELLS) throw new Error(`Grassmannian cup product is capped at ${MAX_EXACT_CELLS} total boxes in this browser page.`);
      const terms = [];
      for (const nu of partitionsOf(total, k, r)) {
        if (!fitsGrassmannianRectangle(nu, r, k)) continue;
        const c = lrCoefficient(lambda, mu, nu);
        if (c) {
          terms.push({ nu, coefficient: c });
          if (terms.length > MAX_GRASSMANNIAN_TERMS) throw new Error(`Grassmannian output exceeded ${MAX_GRASSMANNIAN_TERMS} terms.`);
        }
      }
      terms.rectangle = { r, k, n: r + k };
      return terms.sort(compareTerms);
    }

    function chernZeroPoly() { return new Map(); }

    function chernOnePoly(k) { return new Map([[Array(k).fill(0).join(','), 1]]); }

    function chernVariablePoly(index, k) {
      if (index === 0) return chernOnePoly(k);
      if (index < 0 || index > k) return chernZeroPoly();
      const exps = Array(k).fill(0);
      exps[index - 1] = 1;
      return new Map([[exps.join(','), 1]]);
    }

    function chernAdd(A, B, scaleB = 1, cap = MAX_CHERN_POLY_TERMS) {
      const out = new Map(A);
      for (const [m, c] of B.entries()) {
        const next = (out.get(m) || 0) + scaleB * c;
        if (next === 0) out.delete(m);
        else out.set(m, next);
        if (out.size > cap) throw new Error(`Chern polynomial expansion exceeded ${cap} monomials.`);
      }
      return out;
    }

    function chernMultiply(A, B, k, cap = MAX_CHERN_POLY_TERMS) {
      if (!A.size || !B.size) return chernZeroPoly();
      const out = new Map();
      for (const [ma, ca] of A.entries()) {
        const ea = ma ? ma.split(',').map(Number) : Array(k).fill(0);
        for (const [mb, cb] of B.entries()) {
          const eb = mb ? mb.split(',').map(Number) : Array(k).fill(0);
          const exps = Array.from({ length: k }, (_, i) => (ea[i] || 0) + (eb[i] || 0));
          const keyMono = exps.join(',');
          const next = (out.get(keyMono) || 0) + ca * cb;
          if (next === 0) out.delete(keyMono);
          else out.set(keyMono, next);
          if (out.size > cap) throw new Error(`Chern polynomial expansion exceeded ${cap} monomials.`);
        }
      }
      return out;
    }

    function permutationSign(perm) {
      let inv = 0;
      for (let i = 0; i < perm.length; i++) for (let j = i + 1; j < perm.length; j++) if (perm[i] > perm[j]) inv += 1;
      return inv % 2 ? -1 : 1;
    }

    function determinantPolynomial(matrix, k) {
      const n = matrix.length;
      if (n === 0) return chernOnePoly(k);
      if (n > MAX_CHERN_DETERMINANT_SIZE) throw new Error(`Giambelli determinant expansion is capped at size ${MAX_CHERN_DETERMINANT_SIZE}.`);
      let total = chernZeroPoly();
      const used = Array(n).fill(false);
      const perm = [];
      function rec(row, product) {
        if (!product.size) return;
        if (row === n) {
          total = chernAdd(total, product, permutationSign(perm));
          return;
        }
        for (let col = 0; col < n; col++) {
          if (used[col]) continue;
          used[col] = true;
          perm.push(col);
          rec(row + 1, chernMultiply(product, matrix[row][col], k));
          perm.pop();
          used[col] = false;
        }
      }
      rec(0, chernOnePoly(k));
      return total;
    }

    function giambelliPolynomial(partition, r, k) {
      const nu = trimPartition(partition);
      if (!nu.length) return chernOnePoly(k);
      const ell = Math.min(r, nu.length);
      const matrix = [];
      for (let i = 0; i < ell; i++) {
        const row = [];
        for (let j = 0; j < ell; j++) row.push(chernVariablePoly((nu[i] || 0) + (j + 1) - (i + 1), k));
        matrix.push(row);
      }
      return determinantPolynomial(matrix, k);
    }

    function sympolyNow() {
      return typeof performance !== 'undefined' && performance.now ? performance.now() : Date.now();
    }

    function startSympolyComputationTimer(operation) {
      sympolyComputationCheckCounter = 0;
      sympolyComputationStage = '';
      sympolyComputationDeadline = operation === 'product'
        ? sympolyNow() + SYMPOLY_PRODUCT_TIME_LIMIT_MS
        : 0;
    }

    function clearSympolyComputationTimer() {
      sympolyComputationDeadline = 0;
      sympolyComputationCheckCounter = 0;
      sympolyComputationStage = '';
    }

    function setSympolyComputationStage(stage) {
      sympolyComputationStage = stage || '';
      checkSympolyComputationDeadline(true);
    }

    function checkSympolyComputationDeadline(force = false) {
      if (!sympolyComputationDeadline) return;
      if (!force) {
        sympolyComputationCheckCounter = (sympolyComputationCheckCounter + 1) & 1023;
        if (sympolyComputationCheckCounter) return;
      }
      if (sympolyNow() > sympolyComputationDeadline) {
        const err = new Error('sympoly-timeout');
        err.stage = sympolyComputationStage;
        throw err;
      }
    }

    function sympolyPartitionCount(size) {
      const n = Math.max(0, Math.floor(Number(size) || 0));
      if (sympolyPartitionCountCache.has(n)) return sympolyPartitionCountCache.get(n);
      const dp = Array(n + 1).fill(0n);
      dp[0] = 1n;
      for (let part = 1; part <= n; part++) {
        for (let total = part; total <= n; total++) {
          dp[total] += dp[total - part];
        }
      }
      sympolyPartitionCountCache.set(n, dp[n]);
      return dp[n];
    }

    function sympolyProductPartitionCounts(lambdaRows, muRows) {
      const lambdaSize = sizeOf(trimPartition(lambdaRows));
      const muSize = sizeOf(trimPartition(muRows));
      const totalDegree = lambdaSize + muSize;
      return [
        { label: `p(|lambda|)=p(${lambdaSize})`, size: lambdaSize, count: sympolyPartitionCount(lambdaSize) },
        { label: `p(|mu|)=p(${muSize})`, size: muSize, count: sympolyPartitionCount(muSize) },
        { label: `p(|lambda|+|mu|)=p(${totalDegree})`, size: totalDegree, count: sympolyPartitionCount(totalDegree) },
      ];
    }

    function assertSympolyProductPartitionWithinLimit(lambdaRows, muRows) {
      const counts = sympolyProductPartitionCounts(lambdaRows, muRows);
      const limit = BigInt(SYMPOLY_PRODUCT_PARTITION_LIMIT);
      if (counts.some(item => item.count > limit)) {
        const err = new Error('product-partition-too-large');
        err.partitionCounts = counts;
        throw err;
      }
    }

    function sympolyPartKey(part) {
      return trimPartition(part).join(',');
    }

    function sympolyOutputDegree(operation, lambdaRows, muRows) {
      const lambdaSize = sizeOf(trimPartition(lambdaRows));
      const muSize = sizeOf(trimPartition(muRows));
      return operation === 'plethysm' ? lambdaSize * muSize : lambdaSize + muSize;
    }

    function assertSympolyLinearModeWithinLimit(operation, mode, lambdaRows, muRows) {
      if (mode !== 'linear') return;
      const degree = sympolyOutputDegree(operation, lambdaRows, muRows);
      const data = partitionsOfSizeLimited(degree, SYMPOLY_LINEAR_MODE_PARTITION_LIMIT);
      if (data.truncated) throw new Error('linear-mode-too-large');
    }

    function conversionBasisForSympolyMode(targetBasis, mode) {
      return mode === 'polynomial' && targetBasis === 'm' ? 'p' : targetBasis;
    }

    function partitionsOfSizeLimited(size, limit = SYMPOLY_EXPANSION_PARTITION_LIMIT) {
      if (size === 0) return { parts: [[]], truncated: false };
      const parts = [];
      let truncated = false;
      function gen(rem, maxPart, current) {
        checkSympolyComputationDeadline();
        if (parts.length > limit) {
          truncated = true;
          return;
        }
        if (rem === 0) {
          parts.push(current.slice());
          if (parts.length > limit) truncated = true;
          return;
        }
        for (let p = Math.min(maxPart, rem); p >= 1; p--) {
          current.push(p);
          gen(rem - p, p, current);
          current.pop();
          if (truncated) return;
        }
      }
      gen(size, size, []);
      return { parts: parts.slice(0, limit), truncated };
    }

    function comparePartitionsDesc(a, b) {
      const A = trimPartition(a), B = trimPartition(b);
      const s = sizeOf(B) - sizeOf(A);
      if (s) return s;
      for (let i = 0; i < Math.max(A.length, B.length); i++) {
        const d = (B[i] || 0) - (A[i] || 0);
        if (d) return d;
      }
      return 0;
    }

    function sympolyBigCombSmall(n, k) {
      if (k < 0 || k > n) return 0n;
      k = Math.min(k, n - k);
      let result = 1n;
      for (let i = 1; i <= k; i++) {
        result = (result * BigInt(n - k + i)) / BigInt(i);
      }
      return result;
    }

    function sympolyCapacityGroups(stateCaps) {
      const groups = [];
      for (const cap of stateCaps) {
        if (cap <= 0) continue;
        const last = groups[groups.length - 1];
        if (last && last.cap === cap) last.count++;
        else groups.push({ cap, count: 1 });
      }
      return groups;
    }

    function sympolyGroupAllocationProfiles(cap, count, maxPerColumn) {
      const maxAlloc = maxPerColumn == null ? cap : Math.min(cap, maxPerColumn);
      const cacheKey = `${cap}|${count}|${maxAlloc}`;
      const cached = sympolyGroupProfileCache.get(cacheKey);
      if (cached) return cached;

      const profiles = [];
      const allocationCounts = [];

      function rec(allocation, remainingCount, used) {
        checkSympolyComputationDeadline();
        if (allocation > maxAlloc) {
          if (remainingCount !== 0) return;
          let ways = 1n;
          let unassigned = count;
          const caps = [];
          for (let a = 0; a <= maxAlloc; a++) {
            const take = allocationCounts[a] || 0;
            ways *= sympolyBigCombSmall(unassigned, take);
            unassigned -= take;
            const nextCap = cap - a;
            for (let i = 0; i < take; i++) {
              if (nextCap > 0) caps.push(nextCap);
            }
          }
          profiles.push({ used, caps, ways });
          return;
        }

        for (let take = 0; take <= remainingCount; take++) {
          allocationCounts[allocation] = take;
          rec(allocation + 1, remainingCount - take, used + allocation * take);
        }
        allocationCounts[allocation] = 0;
      }

      rec(0, count, 0);
      sympolyGroupProfileCache.set(cacheKey, profiles);
      return profiles;
    }

    function sympolySortedPositiveState(caps) {
      return caps.filter(c => c > 0).sort((a, b) => b - a);
    }

    function sympolyRowTransitionStates(stateCaps, rowSum, maxPerColumn) {
      const cacheKey = `${stateCaps.join(',')}|${rowSum}|${maxPerColumn == null ? 'inf' : maxPerColumn}`;
      const cached = sympolyRowTransitionCache.get(cacheKey);
      if (cached) return cached;

      const groups = sympolyCapacityGroups(stateCaps);
      const byKey = new Map();

      function rec(groupIndex, used, caps, ways) {
        checkSympolyComputationDeadline();
        if (used > rowSum) return;
        if (groupIndex === groups.length) {
          if (used !== rowSum) return;
          const nextState = sympolySortedPositiveState(caps);
          const k = sympolyPartKey(nextState);
          byKey.set(k, (byKey.get(k) || 0n) + ways);
          return;
        }

        const group = groups[groupIndex];
        for (const profile of sympolyGroupAllocationProfiles(group.cap, group.count, maxPerColumn)) {
          if (used + profile.used > rowSum) continue;
          rec(groupIndex + 1, used + profile.used, caps.concat(profile.caps), ways * profile.ways);
        }
      }

      rec(0, 0, [], 1n);
      const result = [...byKey.entries()].map(([k, ways]) => ({
        state: k ? k.split(',').map(Number) : [],
        ways,
      }));
      sympolyRowTransitionCache.set(cacheKey, result);
      return result;
    }

    function sympolyPowerRowTransitionStates(stateCaps, rowSum) {
      const cacheKey = `${stateCaps.join(',')}|${rowSum}`;
      const cached = sympolyPowerTransitionCache.get(cacheKey);
      if (cached) return cached;

      const groups = sympolyCapacityGroups(stateCaps);
      const byKey = new Map();

      for (let i = 0; i < groups.length; i++) {
        checkSympolyComputationDeadline();
        const group = groups[i];
        if (group.cap < rowSum) continue;
        const caps = [];
        for (let j = 0; j < groups.length; j++) {
          const g = groups[j];
          const count = j === i ? g.count - 1 : g.count;
          for (let c = 0; c < count; c++) caps.push(g.cap);
        }
        const reduced = group.cap - rowSum;
        if (reduced > 0) caps.push(reduced);
        const nextState = sympolySortedPositiveState(caps);
        const k = sympolyPartKey(nextState);
        byKey.set(k, (byKey.get(k) || 0n) + BigInt(group.count));
      }

      const result = [...byKey.entries()].map(([k, ways]) => ({
        state: k ? k.split(',').map(Number) : [],
        ways,
      }));
      sympolyPowerTransitionCache.set(cacheKey, result);
      return result;
    }

    function sympolyCountRowTransitionCoefficient(lambda, mu, transitionForRow) {
      const memo = new Map();

      function rec(rowIndex, stateCaps) {
        checkSympolyComputationDeadline();
        const cacheKey = `${rowIndex}|${stateCaps.join(',')}`;
        if (memo.has(cacheKey)) return memo.get(cacheKey);
        if (rowIndex === lambda.length) {
          const value = stateCaps.length === 0 ? 1n : 0n;
          memo.set(cacheKey, value);
          return value;
        }

        let total = 0n;
        for (const next of transitionForRow(stateCaps, lambda[rowIndex])) {
          total += next.ways * rec(rowIndex + 1, next.state);
        }
        memo.set(cacheKey, total);
        return total;
      }

      return rec(0, trimPartition(mu));
    }

    function sympolyCoefficientForBasis(kind, lambdaRows, muRows) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      if (!lambda.length) return !mu.length ? 1n : 0n;
      if (kind === 'm') return sympolyPartKey(lambda) === sympolyPartKey(mu) ? 1n : 0n;
      if (kind === 's') return BigInt(kostkaNumber(lambda, mu));
      if (kind === 'p') return sympolyCountRowTransitionCoefficient(lambda, mu, sympolyPowerRowTransitionStates);
      if (kind === 'e') return sympolyCountRowTransitionCoefficient(lambda, mu, (stateCaps, rowSum) => sympolyRowTransitionStates(stateCaps, rowSum, 1));
      return sympolyCountRowTransitionCoefficient(lambda, mu, (stateCaps, rowSum) => sympolyRowTransitionStates(stateCaps, rowSum, null));
    }

    function symRatGcd(a, b) {
      a = a < 0n ? -a : a;
      b = b < 0n ? -b : b;
      while (b) {
        const t = a % b;
        a = b;
        b = t;
      }
      return a || 1n;
    }

    function symRat(n, d = 1n) {
      n = BigInt(n);
      d = BigInt(d);
      if (d === 0n) throw new Error('zero denominator');
      if (n === 0n) return { n: 0n, d: 1n };
      if (d < 0n) {
        n = -n;
        d = -d;
      }
      const g = symRatGcd(n, d);
      return { n: n / g, d: d / g };
    }

    function symRatIsZero(a) {
      return a.n === 0n;
    }

    function symRatAdd(a, b) {
      if (a.n === 0n) return b;
      if (b.n === 0n) return a;
      return symRat(a.n * b.d + b.n * a.d, a.d * b.d);
    }

    function symRatSub(a, b) {
      if (b.n === 0n) return a;
      return symRat(a.n * b.d - b.n * a.d, a.d * b.d);
    }

    function symRatMul(a, b) {
      if (a.n === 0n || b.n === 0n) return symRat(0n);
      return symRat(a.n * b.n, a.d * b.d);
    }

    function symRatDiv(a, b) {
      if (b.n === 0n) throw new Error('division by zero');
      return symRat(a.n * b.d, a.d * b.n);
    }

    function symRatFromInteger(value) {
      return symRat(BigInt(value), 1n);
    }

    function sympolyAddLinearTerm(map, part, coeff) {
      if (symRatIsZero(coeff)) return;
      const clean = trimPartition(part);
      const k = sympolyPartKey(clean);
      const existing = map.get(k);
      const next = symRatAdd(existing ? existing.coeff : symRat(0n), coeff);
      if (symRatIsZero(next)) map.delete(k);
      else map.set(k, { part: clean, coeff: next });
    }

    function sympolyBasisLinearCombinationToMonomialVector(sourceTerms, sourceKind, parts) {
      const result = parts.map(() => symRat(0n));
      for (const { coeff, part } of sourceTerms) {
        checkSympolyComputationDeadline();
        if (symRatIsZero(coeff)) continue;
        for (let i = 0; i < parts.length; i++) {
          checkSympolyComputationDeadline();
          const c = sympolyCoefficientForBasis(sourceKind, part, parts[i]);
          if (c !== 0n) {
            result[i] = symRatAdd(result[i], symRatMul(coeff, symRatFromInteger(c)));
          }
        }
      }
      return result;
    }

    function sympolyConvertBasisLinearCombination(sourceTerms, sourceKind, targetKind, parts) {
      if (targetKind === sourceKind) {
        const byKey = new Map();
        for (const { part, coeff } of sourceTerms) {
          checkSympolyComputationDeadline();
          sympolyAddLinearTerm(byKey, part, coeff);
        }
        return [...byKey.values()].sort((a, b) => comparePartitionsDesc(a.part, b.part));
      }

      const rhs = sympolyBasisLinearCombinationToMonomialVector(sourceTerms, sourceKind, parts);
      if (targetKind === 'm') {
        return parts.map((part, i) => {
          checkSympolyComputationDeadline();
          return { part, coeff: rhs[i] };
        });
      }

      if (parts.length > SYMPOLY_BASIS_CONVERSION_LIMIT) {
        throw new Error('basis-conversion-too-large');
      }

      const size = parts.length;
      const matrix = parts.map((mPart, row) => {
        checkSympolyComputationDeadline();
        const values = parts.map(basisPart => {
          checkSympolyComputationDeadline();
          return symRatFromInteger(sympolyCoefficientForBasis(targetKind, basisPart, mPart));
        });
        values.push(rhs[row]);
        return values;
      });

      for (let col = 0; col < size; col++) {
        checkSympolyComputationDeadline(true);
        let pivot = col;
        while (pivot < size && symRatIsZero(matrix[pivot][col])) pivot++;
        if (pivot === size) throw new Error('basis conversion matrix is singular');
        if (pivot !== col) {
          const tmp = matrix[col];
          matrix[col] = matrix[pivot];
          matrix[pivot] = tmp;
        }

        const pivotValue = matrix[col][col];
        for (let j = col; j <= size; j++) matrix[col][j] = symRatDiv(matrix[col][j], pivotValue);

        for (let row = 0; row < size; row++) {
          checkSympolyComputationDeadline();
          if (row === col) continue;
          const factor = matrix[row][col];
          if (symRatIsZero(factor)) continue;
          for (let j = col; j <= size; j++) {
            matrix[row][j] = symRatSub(matrix[row][j], symRatMul(factor, matrix[col][j]));
          }
        }
      }

      return parts.map((part, i) => {
        checkSympolyComputationDeadline();
        return { part, coeff: matrix[i][size] };
      });
    }

    function zeroExponentVector(variableCount) {
      return Array(variableCount).fill(0);
    }

    function polyKey(exponents) {
      return exponents.join(',');
    }

    function exponentsFromKey(polyKeyText) {
      return polyKeyText ? polyKeyText.split(',').map(Number) : [];
    }

    function onePolynomial(variableCount) {
      return new Map([[polyKey(zeroExponentVector(variableCount)), 1n]]);
    }

    function addPolynomialTerm(poly, exponents, coeff = 1n) {
      if (coeff === 0n) return;
      checkSympolyComputationDeadline();
      const k = polyKey(exponents);
      const next = (poly.get(k) || 0n) + coeff;
      if (next === 0n) poly.delete(k);
      else poly.set(k, next);
      if (poly.size > SYMPOLY_POLYNOMIAL_TERM_LIMIT) throw new Error('polynomial-too-large');
    }

    function addScaledPolynomial(target, source, scale = 1n) {
      if (scale === 0n) return target;
      for (const [k, coeff] of source.entries()) {
        checkSympolyComputationDeadline();
        addPolynomialTerm(target, exponentsFromKey(k), coeff * scale);
      }
      return target;
    }

    function multiplyPolynomials(left, right, variableCount) {
      if (!left.size || !right.size) return new Map();
      const product = new Map();
      for (const [leftKey, leftCoeff] of left.entries()) {
        checkSympolyComputationDeadline();
        const leftExp = exponentsFromKey(leftKey);
        for (const [rightKey, rightCoeff] of right.entries()) {
          checkSympolyComputationDeadline();
          const rightExp = exponentsFromKey(rightKey);
          const exp = zeroExponentVector(variableCount);
          for (let i = 0; i < variableCount; i++) exp[i] = leftExp[i] + rightExp[i];
          addPolynomialTerm(product, exp, leftCoeff * rightCoeff);
        }
      }
      return product;
    }

    function multiplyPolynomialList(polys, variableCount) {
      let result = onePolynomial(variableCount);
      for (const poly of polys) {
        checkSympolyComputationDeadline(true);
        result = multiplyPolynomials(result, poly, variableCount);
        if (!result.size) break;
      }
      return result;
    }

    function pSeedPolynomial(k, variableCount) {
      const poly = new Map();
      for (let i = 0; i < variableCount; i++) {
        checkSympolyComputationDeadline();
        const exp = zeroExponentVector(variableCount);
        exp[i] = k;
        addPolynomialTerm(poly, exp);
      }
      return poly;
    }

    function eSeedPolynomial(k, variableCount) {
      if (k > variableCount) return new Map();
      const poly = new Map();
      const exp = zeroExponentVector(variableCount);
      function rec(start, remaining) {
        checkSympolyComputationDeadline();
        if (remaining === 0) {
          addPolynomialTerm(poly, exp);
          return;
        }
        for (let i = start; i <= variableCount - remaining; i++) {
          exp[i] = 1;
          rec(i + 1, remaining - 1);
          exp[i] = 0;
        }
      }
      rec(0, k);
      return poly;
    }

    function hSeedPolynomial(k, variableCount) {
      if (variableCount <= 0) return k === 0 ? onePolynomial(variableCount) : new Map();
      const poly = new Map();
      const exp = zeroExponentVector(variableCount);
      function rec(index, remaining) {
        checkSympolyComputationDeadline();
        if (index === variableCount - 1) {
          exp[index] = remaining;
          addPolynomialTerm(poly, exp);
          exp[index] = 0;
          return;
        }
        for (let a = remaining; a >= 0; a--) {
          exp[index] = a;
          rec(index + 1, remaining - a);
        }
        exp[index] = 0;
      }
      rec(0, k);
      return poly;
    }

    function mPolynomial(partition, variableCount) {
      const lambda = trimPartition(partition);
      if (lambda.length > variableCount) return new Map();
      const values = lambda.concat(Array(variableCount - lambda.length).fill(0));
      const counts = new Map();
      for (const value of values) counts.set(value, (counts.get(value) || 0) + 1);
      const distinctValues = [...counts.keys()].sort((a, b) => b - a);
      const exp = zeroExponentVector(variableCount);
      const poly = new Map();
      function rec(index) {
        checkSympolyComputationDeadline();
        if (index === variableCount) {
          addPolynomialTerm(poly, exp);
          return;
        }
        for (const value of distinctValues) {
          const count = counts.get(value) || 0;
          if (!count) continue;
          counts.set(value, count - 1);
          exp[index] = value;
          rec(index + 1);
          exp[index] = 0;
          counts.set(value, count);
        }
      }
      rec(0);
      return poly;
    }

    function schurPolynomial(lambdaRows, variableCount) {
      const lambda = trimPartition(lambdaRows);
      if (!lambda.length) return onePolynomial(variableCount);
      if (lambda.length > variableCount) return new Map();
      const degree = sizeOf(lambda);
      const { parts, truncated } = partitionsOfSizeLimited(degree);
      if (truncated) throw new Error('polynomial-too-large');
      const result = new Map();
      for (const mu of parts) {
        checkSympolyComputationDeadline();
        if (mu.length > variableCount) continue;
        const coeff = BigInt(kostkaNumber(lambda, mu));
        if (coeff === 0n) continue;
        addScaledPolynomial(result, mPolynomial(mu, variableCount), coeff);
      }
      return result;
    }

    function finiteSympolyPolynomial(kind, partition, variableCount) {
      const lambda = trimPartition(partition);
      if (!lambda.length) return onePolynomial(variableCount);
      if (kind === 'm') return mPolynomial(lambda, variableCount);
      if (kind === 's') return schurPolynomial(lambda, variableCount);
      const seeds = lambda.map(part => {
        if (kind === 'p') return pSeedPolynomial(part, variableCount);
        if (kind === 'e') return eSeedPolynomial(part, variableCount);
        return hSeedPolynomial(part, variableCount);
      });
      return multiplyPolynomialList(seeds, variableCount);
    }

    function exponentPartition(exponents) {
      return exponents.filter(x => x > 0).sort((a, b) => b - a);
    }

    function stableMonomialProductTerms(lambdaRows, muRows) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      if (!lambda.length) return [{ part: mu, coeff: 1n }];
      if (!mu.length) return [{ part: lambda, coeff: 1n }];
      const variableCount = lambda.length + mu.length;
      const product = multiplyPolynomials(mPolynomial(lambda, variableCount), mPolynomial(mu, variableCount), variableCount);
      const byPart = new Map();
      for (const [k, coeff] of product.entries()) {
        checkSympolyComputationDeadline();
        const part = exponentPartition(exponentsFromKey(k));
        const partKey = sympolyPartKey(part);
        if (!byPart.has(partKey)) {
          byPart.set(partKey, { part, coeff });
        } else if (byPart.get(partKey).coeff !== coeff) {
          throw new Error('monomial product collection failed');
        }
      }
      return [...byPart.values()].sort((a, b) => comparePartitionsDesc(a.part, b.part));
    }

    function sympolyExpansionInMonomialBasis(kind, partition, parts) {
      return parts
        .map(part => ({ part, coeff: symRatFromInteger(sympolyCoefficientForBasis(kind, partition, part)) }))
        .filter(term => !symRatIsZero(term.coeff));
    }

    function sympolyMultiplyMonomialLinearTerms(leftTerms, rightTerms) {
      const byKey = new Map();
      for (const left of leftTerms) {
        checkSympolyComputationDeadline(true);
        if (symRatIsZero(left.coeff)) continue;
        for (const right of rightTerms) {
          checkSympolyComputationDeadline();
          if (symRatIsZero(right.coeff)) continue;
          const scale = symRatMul(left.coeff, right.coeff);
          for (const productTerm of stableMonomialProductTerms(left.part, right.part)) {
            checkSympolyComputationDeadline();
            sympolyAddLinearTerm(byKey, productTerm.part, symRatMul(scale, symRatFromInteger(productTerm.coeff)));
          }
        }
      }
      return [...byKey.values()].sort((a, b) => comparePartitionsDesc(a.part, b.part));
    }

    function infiniteSympolyProductTerms(leftKind, rightKind, targetKind, mode, lambdaRows, muRows) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      const totalDegree = sizeOf(lambda) + sizeOf(mu);
      assertSympolyLinearModeWithinLimit('product', mode, lambda, mu);
      assertSympolyProductPartitionWithinLimit(lambda, mu);
      setSympolyComputationStage('enumerating partitions');
      const leftData = partitionsOfSizeLimited(sizeOf(lambda), SYMPOLY_PRODUCT_PARTITION_LIMIT);
      const rightData = partitionsOfSizeLimited(sizeOf(mu), SYMPOLY_PRODUCT_PARTITION_LIMIT);
      const totalData = partitionsOfSizeLimited(totalDegree, SYMPOLY_PRODUCT_PARTITION_LIMIT);
      if (leftData.truncated || rightData.truncated || totalData.truncated) throw new Error('expansion-too-large');

      setSympolyComputationStage('expanding the left factor to monomials');
      const leftTerms = sympolyExpansionInMonomialBasis(leftKind, lambda, leftData.parts);
      checkSympolyComputationDeadline(true);
      setSympolyComputationStage('expanding the right factor to monomials');
      const rightTerms = sympolyExpansionInMonomialBasis(rightKind, mu, rightData.parts);
      checkSympolyComputationDeadline(true);
      setSympolyComputationStage('multiplying monomial-basis terms');
      const monomialTerms = sympolyMultiplyMonomialLinearTerms(leftTerms, rightTerms);
      checkSympolyComputationDeadline(true);
      const conversionBasis = conversionBasisForSympolyMode(targetKind, mode);
      setSympolyComputationStage(`converting to ${conversionBasis}-basis coordinates`);
      return sympolyConvertBasisLinearCombination(monomialTerms, 'm', conversionBasis, totalData.parts);
    }

    function sympolyBasisElementTerms(kind, partition, targetKind) {
      const lambda = trimPartition(partition);
      const data = partitionsOfSizeLimited(sizeOf(lambda));
      if (data.truncated) throw new Error('expansion-too-large');
      return sympolyConvertBasisLinearCombination([{ part: lambda, coeff: symRat(1n) }], kind, targetKind, data.parts);
    }

    function sympolyAddPowerTerm(map, part, coeff) {
      if (symRatIsZero(coeff)) return;
      const clean = trimPartition(part).sort((a, b) => b - a);
      const k = sympolyPartKey(clean);
      const next = symRatAdd(map.get(k) || symRat(0n), coeff);
      if (symRatIsZero(next)) map.delete(k);
      else map.set(k, next);
      if (map.size > SYMPOLY_POLYNOMIAL_TERM_LIMIT) throw new Error('polynomial-too-large');
    }

    function sympolyPowerMapFromTerms(terms) {
      const map = new Map();
      for (const { part, coeff } of terms) sympolyAddPowerTerm(map, part, coeff);
      return map;
    }

    function sympolyPowerTermsFromMap(map) {
      return [...map.entries()]
        .map(([k, coeff]) => ({ part: k ? k.split(',').map(Number) : [], coeff }))
        .sort((a, b) => comparePartitionsDesc(a.part, b.part));
    }

    function sympolyOnePowerMap() {
      return new Map([['', symRat(1n)]]);
    }

    function sympolyMultiplyPowerMaps(left, right) {
      const product = new Map();
      for (const [leftKey, leftCoeff] of left.entries()) {
        const leftPart = leftKey ? leftKey.split(',').map(Number) : [];
        for (const [rightKey, rightCoeff] of right.entries()) {
          const rightPart = rightKey ? rightKey.split(',').map(Number) : [];
          sympolyAddPowerTerm(product, leftPart.concat(rightPart), symRatMul(leftCoeff, rightCoeff));
        }
      }
      return product;
    }

    function sympolyAdamsPowerMap(map, factor) {
      const out = new Map();
      for (const [k, coeff] of map.entries()) {
        const part = k ? k.split(',').map(Number) : [];
        sympolyAddPowerTerm(out, part.map(x => x * factor), coeff);
      }
      return out;
    }

    function sympolyPlethysmPowerTerms(leftKind, rightKind, lambdaRows, muRows) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      const totalDegree = sizeOf(lambda) * sizeOf(mu);
      if (totalDegree > SYMPOLY_PLETHYSM_BOX_LIMIT) throw new Error('plethysm-too-large');

      const outerTerms = sympolyBasisElementTerms(leftKind, lambda, 'p');
      const innerMap = sympolyPowerMapFromTerms(sympolyBasisElementTerms(rightKind, mu, 'p'));
      const total = new Map();

      for (const outer of outerTerms) {
        if (symRatIsZero(outer.coeff)) continue;
        let product = sympolyOnePowerMap();
        for (const part of outer.part) {
          product = sympolyMultiplyPowerMaps(product, sympolyAdamsPowerMap(innerMap, part));
        }
        for (const [k, coeff] of product.entries()) {
          const rho = k ? k.split(',').map(Number) : [];
          sympolyAddPowerTerm(total, rho, symRatMul(outer.coeff, coeff));
        }
      }

      return sympolyPowerTermsFromMap(total);
    }

    function infiniteSympolyPlethysmTerms(leftKind, rightKind, targetKind, mode, lambdaRows, muRows) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      const totalDegree = sizeOf(lambda) * sizeOf(mu);
      assertSympolyLinearModeWithinLimit('plethysm', mode, lambda, mu);
      const totalData = partitionsOfSizeLimited(totalDegree);
      if (totalData.truncated) throw new Error('expansion-too-large');
      const conversionBasis = conversionBasisForSympolyMode(targetKind, mode);
      return sympolyConvertBasisLinearCombination(
        sympolyPlethysmPowerTerms(leftKind, rightKind, lambda, mu),
        'p',
        conversionBasis,
        totalData.parts,
      );
    }

    function oneRationalPolynomial(variableCount) {
      return new Map([[polyKey(zeroExponentVector(variableCount)), symRat(1n)]]);
    }

    function addRationalPolynomialTerm(poly, exponents, coeff) {
      if (symRatIsZero(coeff)) return;
      const k = polyKey(exponents);
      const next = symRatAdd(poly.get(k) || symRat(0n), coeff);
      if (symRatIsZero(next)) poly.delete(k);
      else poly.set(k, next);
      if (poly.size > SYMPOLY_POLYNOMIAL_TERM_LIMIT) throw new Error('polynomial-too-large');
    }

    function addScaledRationalPolynomial(target, source, scale) {
      if (symRatIsZero(scale)) return target;
      for (const [k, coeff] of source.entries()) {
        addRationalPolynomialTerm(target, exponentsFromKey(k), symRatMul(coeff, scale));
      }
      return target;
    }

    function rationalizePolynomial(poly) {
      const out = new Map();
      for (const [k, coeff] of poly.entries()) out.set(k, symRatFromInteger(coeff));
      return out;
    }

    function multiplyRationalPolynomials(left, right, variableCount) {
      if (!left.size || !right.size) return new Map();
      const product = new Map();
      for (const [leftKey, leftCoeff] of left.entries()) {
        const leftExp = exponentsFromKey(leftKey);
        for (const [rightKey, rightCoeff] of right.entries()) {
          const rightExp = exponentsFromKey(rightKey);
          const exp = zeroExponentVector(variableCount);
          for (let i = 0; i < variableCount; i++) exp[i] = leftExp[i] + rightExp[i];
          addRationalPolynomialTerm(product, exp, symRatMul(leftCoeff, rightCoeff));
        }
      }
      return product;
    }

    function adamsRationalPolynomial(poly, factor) {
      const out = new Map();
      for (const [k, coeff] of poly.entries()) {
        addRationalPolynomialTerm(out, exponentsFromKey(k).map(e => e * factor), coeff);
      }
      return out;
    }

    function finiteSympolyPlethysmPolynomial(leftKind, rightKind, lambdaRows, muRows, variableCount) {
      const lambda = trimPartition(lambdaRows);
      const mu = trimPartition(muRows);
      const totalDegree = sizeOf(lambda) * sizeOf(mu);
      if (totalDegree > SYMPOLY_PLETHYSM_BOX_LIMIT) throw new Error('plethysm-too-large');

      const outerTerms = sympolyBasisElementTerms(leftKind, lambda, 'p');
      const innerPoly = rationalizePolynomial(finiteSympolyPolynomial(rightKind, mu, variableCount));
      const total = new Map();

      for (const outer of outerTerms) {
        if (symRatIsZero(outer.coeff)) continue;
        let product = oneRationalPolynomial(variableCount);
        for (const part of outer.part) {
          product = multiplyRationalPolynomials(product, adamsRationalPolynomial(innerPoly, part), variableCount);
        }
        addScaledRationalPolynomial(total, product, outer.coeff);
      }

      return total;
    }

export { conjugatePartition, decomposeTypeAStable, decomposeClassicalStable, decomposeFixedRank, decomposeKronecker, decomposePlethysm, decomposeSchurFunctorFiniteType, semistandardTableaux, kostkaNumber, decomposeGrassmannianCup, giambelliPolynomial, cartanMatrix, positiveRoots, weylOrbitSigned, weylDimensionBigInt, irreducibleCharacterFreudenthal, weightMultiplicityByWeylCharacter, sympolyBasisElementTerms, infiniteSympolyProductTerms, infiniteSympolyPlethysmTerms, finiteSympolyPolynomial, finiteSympolyPlethysmPolynomial, startSympolyComputationTimer, clearSympolyComputationTimer };
