"""Rebuild the reviewed, DOM-free representation kernel from the legacy calculator.

The generated module is committed so static hosting needs no build step. --check
detects upstream changes without modifying files. No legacy page is rewritten.
"""
from pathlib import Path
import re
import sys
import hashlib

ROOT = Path(__file__).resolve().parents[2]
source = (ROOT / 'js/double_young_diagram.js').read_text(encoding='utf-8')
functions = {}
for match in re.finditer(r'^    function (\w+)\(', source, re.M):
    start = match.start()
    line_end = source.index('\n', start)
    first = source[start:line_end]
    if first.rstrip().endswith('}'):
        end = line_end
    else:
        closing = re.search(r'^    }\s*$', source[line_end:], re.M)
        if not closing:
            raise RuntimeError(match.group(1))
        end = line_end + closing.end()
    functions[match.group(1)] = source[start:end].rstrip()

public = '''conjugatePartition decomposeTypeAStable decomposeClassicalStable
decomposeFixedRank decomposeKronecker decomposePlethysm decomposeSchurFunctorFiniteType
semistandardTableaux kostkaNumber decomposeGrassmannianCup giambelliPolynomial
cartanMatrix positiveRoots weylOrbitSigned weylDimensionBigInt
irreducibleCharacterFreudenthal weightMultiplicityByWeylCharacter
sympolyBasisElementTerms infiniteSympolyProductTerms infiniteSympolyPlethysmTerms
finiteSympolyPolynomial finiteSympolyPlethysmPolynomial startSympolyComputationTimer
clearSympolyComputationTimer'''.split()
selected = set(public)
while True:
    added = {name for current in selected for name in functions
             if re.search(r'\b' + re.escape(name) + r'\b', functions[current])}
    if added <= selected:
        break
    selected |= added
body = '\n\n'.join(text for name, text in functions.items() if name in selected)
page_access = r'\b(document|window|sliceState)\b|(?<![\w.])state\s*[.\[]|\$\('
if re.search(page_access, body):
    raise RuntimeError('Kernel dependency closure contains page state: ' + ', '.join(name for name in selected if re.search(page_access, functions[name])))
constants = '\n'.join(re.findall(r'^    const (?:MAX_\w+|SLICE_\w+) = [^;]+;', source, re.M))
constants += '\n' + '\n'.join(re.findall(r'^    const SYMPOLY_\w+ = [^;]+;', source, re.M))
constants += '\n' + '\n'.join(re.findall(r'^    (?:let|const) sympoly(?:Computation\w+|\w*Cache) = [^;]+;', source, re.M))
helpers = '\n'.join(re.findall(r'^    const (?:key|add|sub|scale|dot) = [^\n]+', source, re.M))
output = ('// Generated by extract_legacy.py; source functions remain byte-for-byte equivalent.\n'
          '// Source: js/double_young_diagram.js. Existing limits and numerical caveats apply.\n'
          + constants + '\n' + helpers + '\nconst symmetricCharacterMemo = new Map();\n'
          + body + '\n\nexport { ' + ', '.join(public) + ' };\n')
target = Path(__file__).with_name('representation.mjs')
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8') == output, 'Representation kernel is out of date'
else:
    target.write_text(output, encoding='utf-8')
print(f'Representation kernel: {len(selected)} functions; sha256 {hashlib.sha256(output.encode()).hexdigest()[:16]}')

source = (ROOT / 'js/sheaf_calculator.js').read_text(encoding='utf-8')
functions = {}
for match in re.finditer(r'^  function (\w+)\(', source, re.M):
    start = match.start()
    line_end = source.index('\n', start)
    if source[start:line_end].rstrip().endswith('}'):
        end = line_end
    else:
        closing = re.search(r'^  }\s*$', source[line_end:], re.M)
        end = line_end + closing.end()
    functions[match.group(1)] = source[start:end].rstrip()
public = ['completeIntersectionLineCohomologyAt', 'grassmannianBettiNumbers', 'binomialBigInt', 'buildAbelianHodgeNumbers']
selected = set(public)
while True:
    added = {name for current in selected for name in functions
             if re.search(r'\b' + re.escape(name) + r'\b', functions[current])}
    if added <= selected:
        break
    selected |= added
body = '\n\n'.join(text for name, text in functions.items() if name in selected)
if re.search(r'\b(document|window|state|refs)\b|\$\(', body):
    raise RuntimeError('Sheaf kernel closure contains page state')
output = '// Generated by extract_legacy.py from js/sheaf_calculator.js.\n' + body + '\nexport { ' + ', '.join(public) + ' };\n'
target = Path(__file__).with_name('sheaf_math.mjs')
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8') == output, 'Sheaf kernel is out of date'
else:
    target.write_text(output, encoding='utf-8')
print(f'Sheaf kernel: {len(selected)} functions')

source = (ROOT / 'js/matrix_calculator.js').read_text(encoding='utf-8')
functions = {}
for match in re.finditer(r'^  (?:function|class) (\w+)[ ({]', source, re.M):
    start = match.start()
    line_end = source.index('\n', start)
    if source[start:line_end].rstrip().endswith('}'):
        end = line_end
    else:
        closing = re.search(r'^  }\s*$', source[line_end:], re.M)
        end = line_end + closing.end()
    functions[match.group(1)] = source[start:end].rstrip()
public = ['Complex', 'qrDecomposition', 'svdDecomposition', 'polarDecomposition', 'matrixExp', 'bruhatDecomposition', 'jordanDecomposition']
selected = set(public)
while True:
    added = {name for current in selected for name in functions
             if re.search(r'\b' + re.escape(name) + r'\b', functions[current])}
    if added <= selected:
        break
    selected |= added
body = '\n\n'.join(text for name, text in functions.items() if name in selected)
if re.search(page_access, body):
    raise RuntimeError('Matrix kernel closure contains page state: ' + ', '.join(name for name in selected if re.search(page_access, functions[name])))
constants = '\n'.join(re.findall(r'^  const (?:TOL|DISPLAY_TOL|MAX_SIZE|\w+_TIMEOUT_MS|POLYNOMIAL_ACTION_\w+|DEFAULT_FINITE_FIELD_PRIME) = [^;]+;', source, re.M))
constants += '\n' + re.search(r'^  const SMALL_PRIMES = \[[\s\S]*?\];', source, re.M).group(0)
output = '// Generated by extract_legacy.py from js/matrix_calculator.js.\n' + constants + '\n' + body + '\nexport { ' + ', '.join(public) + ' };\n'
target = Path(__file__).with_name('matrix_math.mjs')
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8') == output, 'Matrix kernel is out of date'
else:
    target.write_text(output, encoding='utf-8')
print(f'Matrix kernel: {len(selected)} functions/classes')
