// Generated by extract_legacy.py from js/sheaf_calculator.js.
  function grassmannianDimension(r, n) {
    return r * Math.max(0, n - r);
  }

  function buildAbelianHodgeNumbers(geometry) {
    const d = geometry.dim;
    return {
      entries: Array.from({ length: d + 1 }, (_, p) => (
        Array.from({ length: d + 1 }, (_, q) => {
          const value = binomialBigInt(d, p) * binomialBigInt(d, q);
          return {
            latex: value.toString(),
            plain: value.toString()
          };
        })
      )),
      message: 'Abelian-variety Hodge numbers.'
    };
  }

  function grassmannianBettiNumbers(r, n) {
    const q = n - r;
    const dim = grassmannianDimension(r, n);
    const counts = Array.from({ length: dim + 1 }, () => 0n);
    const visit = (row, maxPart, total) => {
      if (row === r) {
        counts[total] += 1n;
        return;
      }
      for (let part = maxPart; part >= 0; part -= 1) {
        visit(row + 1, part, total + part);
      }
    };
    visit(0, q, 0);
    return counts;
  }

  function completeIntersectionLineCohomologyAt(ambient, degrees, q, twist) {
    const dim = ambient - degrees.length;
    if (q === 0) {
      if (ambient === degrees.length) return completeIntersectionDegreeProduct(degrees);
      return twist >= 0 ? completeIntersectionHilbertCoefficient(ambient, degrees, twist) : 0n;
    }
    if (q === dim) {
      return completeIntersectionLineCohomologyAt(ambient, degrees, 0, completeIntersectionCanonicalTwist({ ambient, degrees }) - twist);
    }
    return 0n;
  }

  function completeIntersectionCanonicalTwist(geometry) {
    const ambient = Number.isInteger(geometry.ambient) ? geometry.ambient : geometry.dim;
    const degrees = Array.isArray(geometry.degrees) ? geometry.degrees : [];
    return degrees.reduce((sum, degree) => sum + degree, 0) - ambient - 1;
  }

  function completeIntersectionDegreeProduct(degrees) {
    return (degrees || []).reduce((product, degree) => product * BigInt(degree), 1n);
  }

  function completeIntersectionHilbertCoefficient(ambient, degrees, degree) {
    if (!Number.isInteger(degree) || degree < 0) return 0n;
    let total = 0n;
    const count = degrees.length;
    const subsets = 1 << count;
    for (let mask = 0; mask < subsets; mask += 1) {
      let degreeSum = 0;
      let parity = 0;
      for (let i = 0; i < count; i += 1) {
        if (!(mask & (1 << i))) continue;
        degreeSum += degrees[i];
        parity += 1;
      }
      const shifted = degree - degreeSum;
      if (shifted < 0) continue;
      const contribution = binomialBigInt(ambient + shifted, ambient);
      total += parity % 2 === 0 ? contribution : -contribution;
    }
    return total < 0n ? 0n : total;
  }

  function binomialBigInt(n, k) {
    if (!Number.isInteger(n) || !Number.isInteger(k) || k < 0 || k > n) return 0n;
    k = Math.min(k, n - k);
    let out = 1n;
    for (let i = 1; i <= k; i += 1) {
      out = (out * BigInt(n - k + i)) / BigInt(i);
    }
    return out;
  }
export { completeIntersectionLineCohomologyAt, grassmannianBettiNumbers, binomialBigInt, buildAbelianHodgeNumbers };
