// Save this file as theorem_graph_presets/corrections_wait.preset.js
// Add this entry to theorem_graph_presets/presets.js:
// { label: "Corrections wait", key: "corrections_wait", file: "corrections_wait.preset.js" }
window.THEOREM_GRAPH_PRESET_DATA = window.THEOREM_GRAPH_PRESET_DATA || {};
window.THEOREM_GRAPH_PRESET_DATA.corrections_wait = {
  "schemaVersion": 1,
  "title": "Corrections wait",
  "nodes": [
    {
      "id": "n4",
      "type": "example",
      "label": "Sheaf Calculator",
      "setting": "Add related objects: embedding into \\mathbb{P}^n, AJ, ramification locus, actual vector bundle.\nIdentification of some sheaves with others in the step-by-step calculation: ramification locus, \\Omega_{\\mathbb{P}^n}, etc.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 369.2,
      "y": 235.6
    },
    {
      "id": "n6",
      "type": "example",
      "label": "add extra rules",
      "setting": "\\tilde{H}=\\pi^*H; as 2R=\\pi^*(dH), we know R=(d/2)\\tilde{H}.",
      "condition": "\\tilde{H}^3=2; ...",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 424.3,
      "y": 46
    },
    {
      "id": "n11",
      "type": "example",
      "label": "hidden sheaves",
      "setting": "Sometimes relative tangent/cotangent sheaves are easier than the other ones; then there is no need to construct hidden sheaves.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 553.4,
      "y": 88.5
    },
    {
      "id": "n12",
      "type": "example",
      "label": "further examples",
      "setting": "tensor product;\n\\Omega^i;\n\\bigwedge^i T;\nBott formula",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 126.2,
      "y": 224
    },
    {
      "id": "n13",
      "type": "example",
      "label": "Theorem Graph Calculator",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 422.8,
      "y": 385.5
    },
    {
      "id": "n14",
      "type": "example",
      "label": "blank",
      "setting": "Some computers still cannot put a blank in the title.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 504.7,
      "y": 574
    },
    {
      "id": "n15",
      "type": "example",
      "label": "add extra terms",
      "setting": "add a proof sketch in the node; add a remark in the arrow; \ntextbox automatically extend if it is longer",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 628.4,
      "y": 469.8
    },
    {
      "id": "n16",
      "type": "example",
      "label": "reference",
      "setting": "open BibTeX should be open link(we don't know if it is a bibtex document)",
      "condition": "web source don't need bibtex though",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 234.6,
      "y": 507.1
    },
    {
      "id": "n17",
      "type": "example",
      "label": "update",
      "setting": "automatically update; the update button is just to make sure not missing, you can also add a cancel button to simulate the case user don't like the change and want to come back.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 347.5,
      "y": 574
    },
    {
      "id": "n18",
      "type": "example",
      "label": "game of 2048",
      "setting": "I would like the game simulate the game of 2048, each round 2 numbers are randomly generated (90% it is 2, 9% it is 4, 0.9% it is 8, 0.07 it is 16, 0.03% it is 32). User can choose one direction to slide.",
      "condition": "The difference of this game is that, it uses the glued boundary mode in mosaic_calculator.html, so the numbers can slide over the glued boundary and continue moving. This makes the logic for move and merge more complicated.",
      "result": "My current thought is that, the code will record how many times a number cross the glued boundary in a round, denoted by $k_i$. If the number is >10, then the number will explode to avoid infinite loops. You can also imagine that crossing the glued boundary has a small interval time passing, so they are moved in the order of this number $k_i$. If both numbers are the same and they are going to collide in one block from the different position, they will also explode.",
      "proofSketch": "The explode range will depend on the smaller number, if it is >64, than all numbers in tiles near the explode tile will be removed; otherwise, only the number in the explode tile will be removed.",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 94.2,
      "y": 467.3
    },
    {
      "id": "n19",
      "type": "example",
      "label": "presets of glued boundary",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 202.8,
      "y": 309.3
    },
    {
      "id": "n20",
      "type": "example",
      "label": "SES",
      "setting": "if user chooses three sheaves by themselves, there will be an extra choice asking user which one is more difficult to realize",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 574.8,
      "y": 210.9
    },
    {
      "id": "n21",
      "type": "example",
      "label": "Mosaic calculator",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 306,
      "y": 357.7
    },
    {
      "id": "n22",
      "type": "example",
      "label": "Seifert surface",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 536.2,
      "y": 350.9
    },
    {
      "id": "n23",
      "type": "example",
      "label": "vanishing of some terms",
      "setting": "{\n  \"schema\": \"sheaf-calculator-preset\",\n  \"version\": 1,\n  \"exportedAt\": \"2026-06-30T15:51:58.674Z\",\n  \"active\": {\n    \"mode\": \"modify\",\n    \"kind\": \"sheaf\",\n    \"varietyId\": \"X1\",\n    \"sheafId\": \"E8\"\n  },\n  \"options\": {\n    \"repeatNames\": true,\n    \"repeatStyle\": \"letters\",\n    \"classBasis\": \"chern\",\n    \"rootForm\": \"product\",\n    \"classTermOnly\": true,\n    \"classTermIndex\": 2,\n    \"classFamilies\": [\n      \"chern\",\n      \"character\",\n      \"todd\"\n    ],\n    \"hodgeCellSize\": 20,\n    \"revealedCharts\": {\n      \"classes\": true\n    },\n    \"homologyRulePasses\": 2,\n    \"homologyMapInputMode\": \"coefficients\",\n    \"homologyExpressionTransposed\": true,\n    \"exportScope\": \"main\"\n  },\n  \"objects\": {\n    \"varieties\": [\n      {\n        \"id\": \"X1\",\n        \"type\": \"complete-intersection\",\n        \"dim\": \"2\",\n        \"name\": \"X_{4}\",\n        \"genus\": \"g\",\n        \"ppavGenus\": \"2\",\n        \"ciDegrees\": \"4\",\n        \"ciAmbient\": \"3\",\n        \"symmetricProductM\": \"3\",\n        \"symmetricProductGenus\": \"g\",\n        \"grassmannianR\": \"2\",\n        \"grassmannianN\": \"4\",\n        \"homology\": {\n          \"classes\": {\n            \"unit\": {\n              \"symbol\": \"1\"\n            },\n            \"point\": {\n              \"symbol\": \"[p]\"\n            },\n            \"hyperplane\": {\n              \"symbol\": \"H\"\n            }\n          },\n          \"rules\": [\n            {\n              \"id\": \"top-hyperplane-point\",\n              \"builtin\": true,\n              \"enabled\": true,\n              \"lhs\": {\n                \"powers\": {\n                  \"homology_v_X1_H\": 2\n                }\n              },\n              \"rhs\": [\n                {\n                  \"coefficient\": \"4\",\n                  \"powers\": {\n                    \"homology_v_X1_point\": 1\n                  }\n                }\n              ]\n            },\n            {\n              \"id\": \"map-rule-pullback_M4_hyperplane\",\n              \"enabled\": true,\n              \"lhs\": {\n                \"powers\": {\n                  \"map_pullback_M4_homology_v_X3_H\": 1\n                }\n              },\n              \"rhs\": [\n                {\n                  \"coefficient\": \"1\",\n                  \"powers\": {\n                    \"homology_v_X1_H\": 1\n                  }\n                }\n              ]\n            }\n          ]\n        },\n        \"labelX\": 0.22032305743243244,\n        \"labelY\": 0.6007114955357142,\n        \"labelPositionDirty\": true\n      },\n      {\n        \"id\": \"X3\",\n        \"type\": \"projective\",\n        \"dim\": \"3\",\n        \"name\": \"\\\\mathbb{P}^{3}\",\n        \"genus\": \"g\",\n        \"ppavGenus\": \"2\",\n        \"ciDegrees\": \"\",\n        \"ciAmbient\": \"3\",\n        \"symmetricProductM\": \"3\",\n        \"symmetricProductGenus\": \"g\",\n        \"grassmannianR\": \"2\",\n        \"grassmannianN\": \"4\",\n        \"homology\": {\n          \"classes\": {\n            \"unit\": {\n              \"symbol\": \"1\"\n            },\n            \"hyperplane\": {\n              \"symbol\": \"H\"\n            },\n            \"point\": {\n              \"symbol\": \"[p]\"\n            }\n          },\n          \"rules\": [\n            {\n              \"id\": \"top-hyperplane-point\",\n              \"builtin\": true,\n              \"enabled\": true,\n              \"lhs\": {\n                \"powers\": {\n                  \"homology_v_X3_H\": 3\n                }\n              },\n              \"rhs\": [\n                {\n                  \"coefficient\": \"1\",\n                  \"powers\": {\n                    \"homology_v_X3_point\": 1\n                  }\n                }\n              ]\n            }\n          ]\n        },\n        \"labelX\": 0.36864864864864866,\n        \"labelY\": 0.6\n      }\n    ],\n    \"sheaves\": [\n      {\n        \"id\": \"E5\",\n        \"type\": \"tangent\",\n        \"name\": \"\\\\mathcal{T}_{X_{4}}\",\n        \"twist\": \"1\",\n        \"rank\": \"2\",\n        \"baseVarietyId\": \"X1\",\n        \"basis\": \"chern\",\n        \"hiddenOnCanvas\": true,\n        \"labelX\": 0.08,\n        \"labelY\": 0.1957114955357142\n      },\n      {\n        \"id\": \"E6\",\n        \"type\": \"tangent\",\n        \"name\": \"\\\\mathcal{T}_{\\\\mathbb{P}^{3}}\",\n        \"twist\": \"1\",\n        \"rank\": \"3\",\n        \"baseVarietyId\": \"X3\",\n        \"basis\": \"chern\",\n        \"hiddenOnCanvas\": true,\n        \"labelX\": 0.3986486486486487,\n        \"labelY\": 0.39999999999999997\n      },\n      {\n        \"id\": \"E7\",\n        \"type\": \"abstract\",\n        \"name\": \"f^{*}\\\\mathcal{T}_{\\\\mathbb{P}^{3}}\",\n        \"twist\": \"1\",\n        \"rank\": \"3\",\n        \"baseVarietyId\": \"X1\",\n        \"basis\": \"chern\",\n        \"construction\": {\n          \"type\": \"pullback\",\n          \"mapId\": \"M4\",\n          \"sheafId\": \"E6\",\n          \"exact\": true,\n          \"defaultName\": \"f^{*}\\\\mathcal{T}_{\\\\mathbb{P}^{3}}\"\n        },\n        \"hiddenOnCanvas\": true,\n        \"labelX\": 0.22032305743243244,\n        \"labelY\": 0.1957114955357142\n      },\n      {\n        \"id\": \"E8\",\n        \"type\": \"abstract\",\n        \"name\": \"\\\\mathcal{N}_{X_{4}/\\\\mathbb{P}^{3}}\",\n        \"twist\": \"1\",\n        \"rank\": \"1\",\n        \"baseVarietyId\": \"X1\",\n        \"basis\": \"chern\",\n        \"construction\": {\n          \"type\": \"ses-term\",\n          \"role\": \"quotient\",\n          \"sourceSheafIds\": [\n            \"E5\",\n            \"E7\"\n          ],\n          \"normalBundleMapId\": \"M4\",\n          \"sourceTangentSheafId\": \"E5\",\n          \"targetTangentSheafId\": \"E6\",\n          \"pulledTargetTangentSheafId\": \"E7\",\n          \"cleanEmbeddingConfirmed\": true,\n          \"defaultName\": \"\\\\mathcal{N}_{X_{4}/\\\\mathbb{P}^{3}}\",\n          \"sequenceId\": \"S9\",\n          \"inclusionMapId\": \"M10\",\n          \"quotientMapId\": \"M11\"\n        },\n        \"labelX\": 0.2095069679054054,\n        \"labelY\": 0.4076590401785714,\n        \"labelPositionDirty\": true\n      },\n      {\n        \"id\": \"E12\",\n        \"type\": \"twist\",\n        \"name\": \"\\\\mathcal{O}_{\\\\mathbb{P}^{3}}(2)\",\n        \"twist\": \"2\",\n        \"rank\": \"1\",\n        \"baseVarietyId\": \"X3\",\n        \"basis\": \"chern\",\n        \"labelX\": 0.5056756756756757,\n        \"labelY\": 0.39999999999999997\n      },\n      {\n        \"id\": \"E13\",\n        \"type\": \"abstract\",\n        \"name\": \"f^{*}\\\\mathcal{O}_{\\\\mathbb{P}^{3}}(2)\",\n        \"twist\": \"1\",\n        \"rank\": \"1\",\n        \"baseVarietyId\": \"X1\",\n        \"basis\": \"chern\",\n        \"construction\": {\n          \"type\": \"pullback\",\n          \"mapId\": \"M4\",\n          \"sheafId\": \"E12\",\n          \"exact\": true,\n          \"defaultName\": \"f^{*}\\\\mathcal{O}_{\\\\mathbb{P}^{3}}(2)\"\n        },\n        \"labelX\": 0.29510135135135135,\n        \"labelY\": 0.3755440848214286,\n        \"labelPositionDirty\": true\n      }\n    ],\n    \"maps\": [\n      {\n        \"id\": \"M4\",\n        \"name\": \"f\",\n        \"domainKind\": \"variety\",\n        \"domainId\": \"X1\",\n        \"codomainKind\": \"variety\",\n        \"codomainId\": \"X3\",\n        \"curve\": {\n          \"type\": \"straight\"\n        },\n        \"defaultBendPx\": 0,\n        \"labelOffset\": -18,\n        \"labelT\": 0.5\n      },\n      {\n        \"id\": \"M10\",\n        \"name\": \"\\\\iota\",\n        \"domainKind\": \"sheaf\",\n        \"domainId\": \"E5\",\n        \"codomainKind\": \"sheaf\",\n        \"codomainId\": \"E7\",\n        \"construction\": {\n          \"type\": \"short-exact-sequence-map\",\n          \"sequenceId\": \"S9\",\n          \"position\": 0,\n          \"defaultName\": \"\\\\iota\",\n          \"sheafIds\": [\n            \"E5\",\n            \"E7\",\n            \"E8\"\n          ]\n        },\n        \"hiddenOnCanvas\": true,\n        \"labelOffset\": -16,\n        \"labelT\": 0.5\n      },\n      {\n        \"id\": \"M11\",\n        \"name\": \"\\\\pi\",\n        \"domainKind\": \"sheaf\",\n        \"domainId\": \"E7\",\n        \"codomainKind\": \"sheaf\",\n        \"codomainId\": \"E8\",\n        \"construction\": {\n          \"type\": \"short-exact-sequence-map\",\n          \"sequenceId\": \"S9\",\n          \"position\": 1,\n          \"defaultName\": \"\\\\pi\",\n          \"sheafIds\": [\n            \"E5\",\n            \"E7\",\n            \"E8\"\n          ]\n        },\n        \"hiddenOnCanvas\": true,\n        \"labelOffset\": -16,\n        \"labelT\": 0.5\n      }\n    ],\n    \"sequences\": [\n      {\n        \"id\": \"S9\",\n        \"type\": \"short-exact-sequence\",\n        \"sheafIds\": [\n          \"E5\",\n          \"E7\",\n          \"E8\"\n        ],\n        \"mapIds\": [\n          \"M10\",\n          \"M11\"\n        ],\n        \"baseVarietyId\": \"X1\",\n        \"tail\": {\n          \"pointCount\": 0,\n          \"hiddenOnCanvas\": true\n        }\n      }\n    ]\n  },\n  \"hidden\": [\n    {\n      \"kind\": \"sheaf\",\n      \"id\": \"E5\"\n    },\n    {\n      \"kind\": \"sheaf\",\n      \"id\": \"E6\"\n    },\n    {\n      \"kind\": \"sheaf\",\n      \"id\": \"E7\"\n    },\n    {\n      \"kind\": \"map\",\n      \"id\": \"M10\"\n    },\n    {\n      \"kind\": \"map\",\n      \"id\": \"M11\"\n    },\n    {\n      \"kind\": \"sequence-tail\",\n      \"id\": \"S9\"\n    }\n  ],\n  \"nextObjectIndex\": 14\n}",
      "condition": "In characteristic class chart, when user set \"terms\" to check the i-th term only, some columns are missing when they are 0. It should show 0 rather than missing.",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 188.1,
      "y": 116.5
    },
    {
      "id": "n24",
      "type": "example",
      "label": "identify",
      "setting": "The user can not pick the sheaf/varieties or cancel the status. There is a bug.",
      "condition": "I would also like user being able to set sheaf identification only as a rule.",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 286.9,
      "y": 46
    },
    {
      "id": "n25",
      "type": "example",
      "label": "hypersurface",
      "setting": "add the normal sheaf identification rule for the hypersurface.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 694.4,
      "y": 270.3
    }
  ],
  "arrows": [
    {
      "id": "a3",
      "sourceId": "n6",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a7",
      "sourceId": "n11",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a8",
      "sourceId": "n12",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a9",
      "sourceId": "n14",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a10",
      "sourceId": "n15",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a11",
      "sourceId": "n16",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a12",
      "sourceId": "n17",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a13",
      "sourceId": "n19",
      "targetId": "n18",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "none",
      "level": 2,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a14",
      "sourceId": "n20",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a15",
      "sourceId": "n18",
      "targetId": "n21",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "none",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a16",
      "sourceId": "n22",
      "targetId": "n21",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "none",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a17",
      "sourceId": "n23",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a18",
      "sourceId": "n24",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a20",
      "sourceId": "n11",
      "targetId": "n25",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "none",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    }
  ],
  "references": [
    {
      "key": "hartshorne1977",
      "author": "Hartshorne, Robin",
      "title": "Algebraic Geometry",
      "year": "1977",
      "citeText": "\\cite{hartshorne1977}",
      "url": "",
      "source": "bibtex",
      "rawBibtex": "@book{hartshorne1977,\n author = {Hartshorne, Robin},\n title = {Algebraic Geometry},\n year = {1977}\n}"
    },
    {
      "key": "Bott",
      "author": "",
      "title": "Bott formula",
      "year": "",
      "citeText": "",
      "url": "https://claude.ai/share/142d0460-e54e-4671-9d5e-ac10c469a87b",
      "source": "web",
      "rawBibtex": ""
    },
    {
      "key": "Seif",
      "author": "",
      "title": "Seifert surface",
      "year": "",
      "citeText": "",
      "url": "https://chatgpt.com/share/6a43e149-99ac-83eb-9da5-90b552a3c5c8",
      "source": "web",
      "rawBibtex": ""
    },
    {
      "key": "normal bundle",
      "author": "",
      "title": "normal bundle of hypersurface",
      "year": "",
      "citeText": "",
      "url": "https://chatgpt.com/share/6a43e9be-c214-83eb-95ad-5540eb27b907",
      "source": "web",
      "rawBibtex": ""
    }
  ],
  "view": {
    "selectedId": "n12",
    "selectedReferenceKeys": [],
    "layoutRunning": false
  }
};

