// Save this file as theorem_graph_presets/corrections_wait.preset.js
// Add this entry to theorem_graph_presets/presets.js:
// { label: "Corrections wait", key: "corrections_wait", file: "corrections_wait.preset.js" }
window.THEOREM_GRAPH_PRESET_DATA = window.THEOREM_GRAPH_PRESET_DATA || {};
window.THEOREM_GRAPH_PRESET_DATA.corrections_wait = {
  "schemaVersion": 1,
  "title": "Corrections wait",
  "nodes": [
    {
      "id": "n4",
      "type": "example",
      "label": "Sheaf Calculator",
      "setting": "Add related objects: embedding into \\mathbb{P}^n, AJ, ramification locus, actual vector bundle.\nIdentification of some sheaves with others in the step-by-step calculation: ramification locus, \\Omega_{\\mathbb{P}^n}, etc.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 413.9,
      "y": 204.6
    },
    {
      "id": "n6",
      "type": "example",
      "label": "add extra rules",
      "setting": "\\tilde{H}=\\pi^*H; as 2R=\\pi^*(dH), we know R=(d/2)\\tilde{H}.",
      "condition": "\\tilde{H}^3=2; ...",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 323.1,
      "y": 107.9
    },
    {
      "id": "n11",
      "type": "example",
      "label": "hidden sheaves",
      "setting": "Sometimes relative tangent/cotangent sheaves are easier than the other ones; then there is no need to construct hidden sheaves.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 513.3,
      "y": 93
    },
    {
      "id": "n12",
      "type": "example",
      "label": "further examples",
      "setting": "tensor product;\n\\Omega^i;\n\\bigwedge^i T;\nBott formula",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 212.5,
      "y": 128.7
    },
    {
      "id": "n13",
      "type": "example",
      "label": "Theorem Graph Calculator",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 350.3,
      "y": 320.3
    },
    {
      "id": "n14",
      "type": "example",
      "label": "blank",
      "setting": "Some computers still cannot put a blank in the title.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 621.8,
      "y": 336.7
    },
    {
      "id": "n15",
      "type": "example",
      "label": "add extra terms",
      "setting": "add a proof sketch in the node; add a remark in the arrow; \ntextbox automatically extend if it is longer",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef7f4",
      "x": 474,
      "y": 374
    },
    {
      "id": "n16",
      "type": "example",
      "label": "reference",
      "setting": "open BibTeX should be open link(we don't know if it is a bibtex document)",
      "condition": "web source don't need bibtex though",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 155.4,
      "y": 374
    },
    {
      "id": "n17",
      "type": "example",
      "label": "update",
      "setting": "automatically update; the update button is just to make sure not missing, you can also add a cancel button to simulate the case user don't like the change and want to come back.",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#2f5f9f",
      "fillColor": "#eef4fb",
      "x": 296.8,
      "y": 374
    },
    {
      "id": "n18",
      "type": "example",
      "label": "game of 2048",
      "setting": "I would like the game simulate the game of 2048, each round 2 numbers are randomly generated (90% it is 2, 9% it is 4, 0.9% it is 8, 0.07 it is 16, 0.03% it is 32). User can choose one direction to slide.",
      "condition": "The difference of this game is that, it uses the glued boundary mode in mosaic_calculator.html, so the numbers can slide over the glued boundary and continue moving. This makes the logic for move and merge more complicated.",
      "result": "My current thought is that, the code will record how many times a number cross the glued boundary in a round, denoted by $k_i$. If the number is >10, then the number will explode to avoid infinite loops. You can also imagine that crossing the glued boundary has a small interval time passing, so they are moved in the order of this number $k_i$. If both numbers are the same and they are going to collide in one block from the different position, they will also explode.",
      "proofSketch": "The explode range will depend on the smaller number, if it is >64, than all numbers in tiles near the explode tile will be removed; otherwise, only the number in the explode tile will be removed.",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 176,
      "y": 231.5
    },
    {
      "id": "n19",
      "type": "example",
      "label": "presets of glued boundary",
      "setting": "",
      "condition": "",
      "result": "",
      "proofSketch": "",
      "citationKeys": [],
      "color": "#7a6f65",
      "fillColor": "#f7f5f1",
      "x": 393.9,
      "y": 265.5
    }
  ],
  "arrows": [
    {
      "id": "a3",
      "sourceId": "n6",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a7",
      "sourceId": "n11",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a8",
      "sourceId": "n12",
      "targetId": "n4",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a9",
      "sourceId": "n14",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a10",
      "sourceId": "n15",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a11",
      "sourceId": "n16",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a12",
      "sourceId": "n17",
      "targetId": "n13",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "hook",
      "level": 1,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    },
    {
      "id": "a13",
      "sourceId": "n19",
      "targetId": "n18",
      "label": "",
      "remark": "",
      "body": "solid",
      "head": "arrow",
      "tail": "none",
      "level": 2,
      "endpointScale": 1,
      "curve": 0,
      "labelOffset": 0,
      "color": "#5f574e"
    }
  ],
  "references": [
    {
      "key": "hartshorne1977",
      "author": "Hartshorne, Robin",
      "title": "Algebraic Geometry",
      "year": "1977",
      "citeText": "\\cite{hartshorne1977}",
      "url": "",
      "source": "bibtex",
      "rawBibtex": "@book{hartshorne1977,\n author = {Hartshorne, Robin},\n title = {Algebraic Geometry},\n year = {1977}\n}"
    },
    {
      "key": "Bott",
      "author": "",
      "title": "Bott formula",
      "year": "",
      "citeText": "",
      "url": "https://claude.ai/share/142d0460-e54e-4671-9d5e-ac10c469a87b",
      "source": "web",
      "rawBibtex": ""
    }
  ],
  "view": {
    "selectedId": "n18",
    "selectedReferenceKeys": [],
    "layoutRunning": false
  }
};